### ISSUE TITLE
Caching messages

### ISSUE THREAD

**Issue by Thesoce60** [Enough-Software/enough_mail#100]
I have tried to save in tempDirectory MimeMessage body raw but when I assign the bodyraw to a new MimeMessage this message will not be parsed but I have used the .parse() function

**Comment by robert-virkus** [comment]
Hi, the `MimeMessage.bodyRaw` field is somewhat problematic, as for example header information is stripped away when parsing the messages. In most cases you should be fine using `final text = MimeMessage.renderMessage()` for converting the message to the textual form and then use `Message()..bodyRaw = text` to convert the message back.
