### ISSUE TITLE
SMTP Auth Failure With Office365 Account

### ISSUE THREAD

**Issue by DaylinBehr** [Enough-Software/enough_mail#106]
Hi, this is a great mailing package. 

I've just picked up on an issue that I cannot seem to wrap my head around.

I used the SMTP example code provided but switched the smtp credentials to the following:

````
String smtpServerHost = 'smtp.office365.com';
int smtpServerPort = 587;
bool isSmtpServerSecure = false;
````

Then I tried calling the below smtpExample method asynchronously.

```
Future<void> smtpExample() async {
  final client = SmtpClient('enough.de', isLogEnabled: true);
  try {
    await client.connectToServer(smtpServerHost, smtpServerPort,
        isSecure: isSmtpServerSecure);
    await client.ehlo();
    // await client.startTls();
    var loginResponse = await client.login('user.name', 'password');
    print('login response is ${loginResponse.isOkStatus}');
    if (loginResponse.isOkStatus) {
      final builder = MessageBuilder.prepareMultipartAlternativeMessage();
      builder.from = [MailAddress('My name', 'user.name')];
      builder.to = [MailAddress('Your name', 'myEmail@domain.com')];
      builder.subject = 'My first message';
      builder.addTextPlain('hello world.');
      builder.addTextHtml('<p>hello <b>world</b></p>');
      final mimeMessage = builder.buildMimeMessage();
      final sendResponse = await client.sendMessage(mimeMessage);
      print('message sent: ${sendResponse.isOkStatus}');
    }
  } on SmtpException catch (e) {
    print('SMTP failed with $e');
  }
}
```

```
void main() async {
//  await discoverExample();
//  await imapExample();
  await smtpExample();
//  await popExample();
//  exit(0);
  runApp(MyApp());
}
```

After calling it this is the log response:

```
I/flutter (16316): A: connecting to server smtp.office365.com:587 - secure: false
I/flutter (16316): S: 220 CT2P275CA0015.outlook.office365.com Microsoft ESMTP MAIL Service ready at Tue, 12 Jan 2021 10:24:19 +0000
I/flutter (16316): A: SMTP: got server greeting 220 CT2P275CA0015.outlook.office365.com Microsoft ESMTP MAIL Service ready at Tue, 12 Jan 2021 10:24:19 +0000
I/flutter (16316): C: EHLO enough.de
I/flutter (16316): S: 250-CT2P275CA0015.outlook.office365.com Hello [102.182.14.214]
I/flutter (16316): S: 250-SIZE 157286400
I/flutter (16316): S: 250-PIPELINING
I/flutter (16316): S: 250-DSN
I/flutter (16316): S: 250-ENHANCEDSTATUSCODES
I/flutter (16316): S: 250-STARTTLS
I/flutter (16316): S: 250-8BITMIME
I/flutter (16316): S: 250-BINARYMIME
I/flutter (16316): S: 250-CHUNKING
I/flutter (16316): S: 250 SMTPUTF8
I/flutter (16316): S: 
I/flutter (16316): C: AUTH PLAIN <password scrambled>
I/flutter (16316): S: 504 5.7.4 Unrecognized authentication type [CT2P275CA0015.ZAFP275.PROD.OUTLOOK.COM]
I/flutter (16316): S: 
I/flutter (16316): SMTP failed with 504 5.7.4 Unrecognized authentication type [CT2P275CA0015.ZAFP275.PROD.OUTLOOK.COM]

```

Now I am unsure as to why it responds with an unrecognized authentication type. The same happens if I replace the login credentials with an actual office 365 account.

Any help would be appreciated.

**Comment by robert-virkus** [comment]
Hi, as you can see from the output (as well from `smtpClient.serverInfo.supportsStartTls` from v0.1.0 onward) the server supports STARTTLS, so you have to switch to TLS first. You can do that with `await smtpClient.startTls()`.

Hope this helps,
yours
  Robert

**Comment by DaylinBehr** [comment]
Hi Robert

Thanks for the speedy reply.

I uncommented client.startTls() and it did switch however I face the same error but I think it may be due to OAuth this time around?

Here's the log:

```
I/flutter (16316): A: connecting to server smtp.office365.com:587 - secure: false
I/flutter (16316): S: 220 CTXP275CA0023.outlook.office365.com Microsoft ESMTP MAIL Service ready at Tue, 12 Jan 2021 11:20:12 +0000
I/flutter (16316): A: SMTP: got server greeting 220 CTXP275CA0023.outlook.office365.com Microsoft ESMTP MAIL Service ready at Tue, 12 Jan 2021 11:20:12 +0000
I/flutter (16316): C: EHLO enough.de
I/flutter (16316): S: 250-CTXP275CA0023.outlook.office365.com Hello [102.182.14.214]
I/flutter (16316): S: 250-SIZE 157286400
I/flutter (16316): S: 250-PIPELINING
I/flutter (16316): S: 250-DSN
I/flutter (16316): S: 250-ENHANCEDSTATUSCODES
I/flutter (16316): S: 250-STARTTLS
I/flutter (16316): S: 250-8BITMIME
I/flutter (16316): S: 250-BINARYMIME
I/flutter (16316): S: 250-CHUNKING
I/flutter (16316): S: 250 SMTPUTF8
I/flutter (16316): S: 
I/flutter (16316): C: STARTTLS // Switches over to STARTTLS here
I/flutter (16316): S: 220 2.0.0 SMTP server ready
I/flutter (16316): S: 
I/flutter (16316): A: STARTTL: upgrading socket to secure one...
I/flutter (16316): A: now using secure connection.
I/flutter (16316): C: EHLO enough.de
I/flutter (16316): S: 250-CTXP275CA0023.outlook.office365.com Hello [102.182.14.214]
I/flutter (16316): S: 250-SIZE 157286400
I/flutter (16316): S: 250-PIPELINING
I/flutter (16316): S: 250-DSN
I/flutter (16316): S: 250-ENHANCEDSTATUSCODES
I/flutter (16316): S: 250-AUTH LOGIN XOAUTH2
I/flutter (16316): S: 250-8BITMIME
I/flutter (16316): S: 250-BINARYMIME
I/flutter (16316): S: 250-CHUNKING
I/flutter (16316): S: 250 SMTPUTF8
I/flutter (16316): S: 
I/flutter (16316): C: AUTH PLAIN <password scrambled>
I/flutter (16316): S: 504 5.7.4 Unrecognized authentication type [CTXP275CA0023.ZAFP275.PROD.OUTLOOK.COM]
I/flutter (16316): S: 
I/flutter (16316): SMTP failed with 504 5.7.4 Unrecognized authentication type [CTXP275CA0023.ZAFP275.PROD.OUTLOOK.COM]
```

If it is due to OAuth then that's a bit odd since using the Dart Mailer package will send the email via SMTP with standard login.

**Comment by robert-virkus** [comment]
Hi, I think you are right about the `XOAUTH2` requirement, the only AUTH reply I see is the `250-AUTH LOGIN XOAUTH2` response. It's very curious how the Dart Mailer packages manages this with a standard login, can you provide more information about how the Dart Mailer package communicates via SMTP here? 

`smtp.office365.com` does only support connecting via port 587 as far as I see and auth options become only available after switching to TLS. Currently `XOAUTH2` is not supported by SMTP, but there is support for it in the IMAP package, which should be relatively simple to adapt - I opened #107 for this.

**Comment by robert-virkus** [comment]
Stupid me, I vaguely remembered that an outlook account worked before, so I tried again: it works. Use the `LOGIN` authentication, like it says there quite clearly: `250-AUTH LOGIN XOAUTH2`. Also `SmtpClient.serverInfo.authMechanisms` lists `AuthMechanism.login` for outlook/office365 accounts.

So, to login just call 
`await smtpClient.auth(userName, password, authMechanism: AuthMechanism.login)` in this case.

Alternatively consider using the high level API with `MailClient` as the high level API does this automatically for you.

Note that I will remove the named parameter `authMechanism` and replace it with an optional positioned parameter shortly, as this is an enumeration anyhow and it feels stupid to write it twice there. So in the future it will be `await smtpClient.auth(userName, password,  AuthMechanism.login)`.

**Comment by DaylinBehr** [comment]
> 
> 
> Stupid me, I vaguely remembered that an outlook account worked before, so I tried again: it works. Use the `LOGIN` authentication, like it says there quite clearly: `250-AUTH LOGIN XOAUTH2`. Also `SmtpClient.serverInfo.authMechanisms` lists `AuthMechanism.login` for outlook/office365 accounts.
> 
> So, to login just call
> `await smtpClient.auth(userName, password, authMechanism: AuthMechanism.login)` in this case.
> 
> Alternatively consider using the high level API with `MailClient` as the high level API does this automatically for you.
> 
> Note that I will remove the named parameter `authMechanism` and replace it with an optional positioned parameter shortly, as this is an enumeration anyhow and it feels stupid to write it twice there. So in the future it will be `await smtpClient.auth(userName, password, AuthMechanism.login)`.

Ah, that makes a lot more sense now! Switching the Auth mechanism from plain to login worked! Thank you very much @robert-virkus 

Oh and just a minor note for anyone in future it would be: 
`yourSMTPClientInstanceVariable.login(userName, password, authMechanism: AuthMechanism.login);`

**Comment by robert-virkus** [comment]
I also deprecated the login method and introduced the authenticate method, to differentiate the authentication from the `login` auth mechanism better, so in the future you can use the deprecated above or:
```dart
await yourSMTPClientInstanceVariable.authenticate(userName, password, AuthMechanism.login);
```
