### ISSUE TITLE
Highlevel search API

### ISSUE THREAD

**Issue by robert-virkus** [Enough-Software/enough_mail#109]
Provide a high level search API with the following search options:

In a nutshell, you can provide various search terms to the server and any messages that match, in the currently selected folder, will be returned. One limitation of the command is that when multiple search terms are specified, they are considered “AND” terms by default, but you can select only two terms to “OR”, and there is no complex logic grouping (i.e. bracketing of terms) – so it’s rather simple in that regard.

Here is a rundown of all the possible criteria that can be specified:

* `ALL`: All messages in the mailbox.
* `ANSWERED`: Messages with the \Answered flag set.
* `BCC <string>`: Messages that contain the specified string in the envelope structure’s BCC field.
* `BEFORE <date>`: Messages whose internal date (disregarding time and timezone) is earlier than the specified date.
* `BODY <string>`: Messages that contain the specified string in the body of the message.
* `CC <string>`: Messages that contain the specified string in the envelope structure’s CC field.
* `DELETED`: Messages with the \Deleted flag set.
* `DRAFT`: Messages with the \Draft flag set.
* `FLAGGED`: Messages with the \Flagged flag set.
* `FROM <string>`: Messages that contain the specified string in the envelope structure’s FROM field.
* `HEADER <field-name> <string>`: Messages that have a header with the specified field-name and which contain the specified string in the text of the header (i.e. what comes after the colon). If the string to search is zero-length, this matches all messages that have a header line with the specified field-name, regardless of the contents.
* `KEYWORD <flag>`: Messages with the specified keyword flag set.
* `LARGER <n>`:  Messages with a size larger than the specified number of octets.
* `NEW`: Messages that have the \Recent flag set but not the \Seen flag.
* `NOT <search-key>`: Messages that do not match the specified search key.
* `OLD`: Messages that do not have the \Recent flag set.
* `ON <date>`: Messages whose internal date (disregarding time and timezone) is within the specified date.
* `OR <search-key1> <search-key2>`: Messages that match either search key.
* `RECENT`: Messages that have the \Recent flag set.
* `SEEN`: Messages that have the \Seen flag set.
* `SENTBEFORE <date>`: Messages whose Date: header (disregarding time and timezone) is earlier than the specified date.
* `SENTON <date>`: Messages whose Date: header (disregarding time and timezone) is within the specified date.
* `SENTSINCE <date>`: Messages whose Date: header (disregarding time and timezone) is within or later than the specified date.
* `SINCE <date>`: Messages whose internal date (disregarding time and timezone) is within or later than the specified date.
* `SMALLER <n>`: Messages with a size smaller than the specified number of octets.
* `SUBJECT <string>`: Messages that contain the specified string in the envelope structure’s SUBJECT field.
* `TEXT <string>`: Messages that contain the specified string in the header or body of the message.
* `TO <string>`: Messages that contain the specified string in the envelope structure’s TO field.
* `UID <sequence set>`: Messages with unique identifiers corresponding to the specified unique identifier set. Sequence set ranges are permitted.
* `UNANSWERED`: Messages that do not have the \Answered flag set.
* `UNDELETED`: Messages that do not have the \Deleted flag set.
* `UNDRAFT`: Messages that do not have the \Draft flag set.
* `UNFLAGGED`: Messages that do not have the \Flagged flag set.
* `UNKEYWORD <flag>`: Messages that do not have the specified keyword flag set.
* `UNSEEN`: Messages that do not have the \Seen flag set.

(source: https://www.atmail.com/blog/imap-commands/)

**Comment by RichardFevrier** [comment]
Hi @robert-virkus I was wondering if there was a way to combine them ? =)
Thanks a lot

**Comment by robert-virkus** [comment]
Hi @RichardFevrier yes, you can :-)

When using the high level `MailClient` just create a `MailSearch` instance in which you define your query:

```dart
const MailSearch(
    this.query,
    this.queryType, {
    this.messageType,
    this.since,
    this.before,
    this.sentSince,
    this.sentBefore,
    this.pageSize = 20,
    this.fetchPreference = FetchPreference.envelope,
  });
```

This will combine all given search terms.

When using the low level `ImapClient`, you can additionallu use the  `SearchQueryBuilder.from(...)` to create a query builder and then add any search terms you need by calling `add(SearchTerm term)`.

Hope this helps?
Best
  Robert

**Comment by RichardFevrier** [comment]
Thanks for the answer @robert-virkus,

I meant for example: using the highlevel abstraction `MailSearch` to search a keyword in the `from` and another in the `body`.
Correct me if I'm wrong but I think this is currently not possible.

I think the highlevel abstraction does a great job to remove the hasle of doing things like `_pauseIdle()`, etc.. but should not prevent the developer to construct his own query.

Creating a string like `FROM "senderName" BODY "keyword"` is just basic right? And it would be too bad to miss all the abstraction you've developed about the `connection`, etc... just for a string.

Best regards,
Richard
