### ISSUE TITLE
Attachment

### ISSUE THREAD

**Issue by barilki** [Enough-Software/enough_mail#125]
I got the search results. How can I get the link to the attachments? 

 final searchResult = await mailClient.searchMessages(MailSearch("shalom",SearchQueryType.body));
      // the first page of search results is already pre-cached:
      for (final msg in searchResult.messages.elements) {
        printMessage(msg);
      }

Thanks!

**Comment by robert-virkus** [comment]
```dart
for (final msg in searchResult.messages.elements) {
  final attachments = msg.findContentInfo(disposition: ContentDisposition.attachment);
}
```

**Comment by barilki** [comment]
When I try to print the list it shows me that the list is empty

**Comment by robert-virkus** [comment]
By default only the IMAP `ENVELOPE` information is precached. So you are right, you would need to download the message contents first to find all attachments.
```dart
for (final msg in searchResult.messages.elements) {
  msg = await mailClient.fetchMessageContents(msg, markAsSeen: true);
  final attachments = msg.findContentInfo(disposition: ContentDisposition.attachment);
  for (final attachment in attachments) {
      final attachmentMimePart = msg.getPart(attachment.fetchId);
     // do something with the attachment
  }
}
```

**Comment by barilki** [comment]
How can I download each attachment to my device?

**Comment by robert-virkus** [comment]
You can call `mimePart.decodeContentBinary()` to retrieve the bytes / `Uint8List` of binary attachments. Here's an example:
```dart
  static MediaProvider fromMime(MimeMessage mimeMessage, MimePart mimePart) {
    final name = mimePart.decodeFileName();
    final mediaType = mimePart.mediaType.text;
    if (mimePart.mediaType?.isText ?? false) {
      return TextMediaProvider(name, mediaType, mimePart.decodeContentText());
    } else {
      return MemoryMediaProvider(
          name, mediaType, mimePart.decodeContentBinary(),
          description: mimeMessage.decodeSubject());
    }
  }
```

Note: in this case a `MemoryMediaProvider` is just a glorified wrapper for an `Uint8List`.
