### ISSUE TITLE
Migrate to null-safety

### ISSUE THREAD

**Issue by robert-virkus** [Enough-Software/enough_mail#127]
Migrate to null-safetey
https://dart.dev/null-safety/migration-guide

- `pub outdated --mode=null-safety`
- `dart pub upgrade --null-safety`
- `dart migrate`
  - use `variable/*!*/`, `variable/*?*/` and `/*late*/variable` hints as required

**Comment by hpoul** [comment]
Any plan on pushing 1.0.0 to pub any time soon? :-) thanks

**Comment by robert-virkus** [comment]
I tested the waters the recent days to make sure not to make any stupid mistakes. 
But done it now.
