### ISSUE TITLE
Invalid timezone [Z] parsing a date

### ISSUE THREAD

**Issue by azulli** [Enough-Software/enough_mail#132]
Hi,
I've encountered an error parsing a date with a Zulu (`Z`) timezone, like "Fri, 25 Dec 2020 08:57:44 Z".
After that the resulting message doesn't have any date set.

Regards and good work.

**Comment by robert-virkus** [comment]
Thanks for the report. "Real" timezones consist of 3 characters, which are expected here. When I finished with #127 I will look into this topic.
