### ISSUE TITLE
IMAP failed with null

### ISSUE THREAD

**Issue by DineshTaral** [Enough-Software/enough_mail#134]
getting an exception as null.

**Comment by robert-virkus** [comment]
Can you provide **any** details? Ideally both your code and the stacktrace.
Thanks.

**Comment by DineshTaral** [comment]
Thanks for quick reply.
I'm using same code provided in example code.

  Future<void> imapExample() async {
    final client = ImapClient(isLogEnabled: false);
    try {
      await client.connectToServer("imap.gmail.com", 993,
          isSecure: true);
      await client.login("mygmail@gmail.com", "mypass");
      final mailboxes = await client.listMailboxes();
      print('mailboxes: $mailboxes');
      await client.selectInbox();
      // fetch 10 most recent messages:
      final fetchResult = await client.fetchRecentMessages(
          messageCount: 10, criteria: 'BODY.PEEK[]');
      for (final message in fetchResult.messages) {
        printMessage(message);
      }
      await client.logout();
    } on ImapException catch (e) {
      print('IMAP failed with ${e.details}');
    }
  }

**Comment by robert-virkus** [comment]
apparently resolved

**Comment by kekko7072** [comment]
I tried using flutter web ad says `A: connecting to server imap.gmail.com:993 - secure: true
unhandled exception Unsupported operation: RawSocket constructor`
I also enabled and created an app specific password but it doesn't work
This is the code
```
 Future imapExample() async {
    final client = ImapClient(isLogEnabled: true);
    try {
      await client.connectToServer("imap.gmail.com", 993, isSecure: true);
      await client.login("User Name", "app password");
      final mailboxes = await client.listMailboxes();
      print('mailboxes: $mailboxes');
      await client.selectInbox();
// fetch 10 most recent messages:
      final fetchResult = await client.fetchRecentMessages(
          messageCount: 10, criteria: 'BODY.PEEK[]');
      for (final message in fetchResult.messages) {
        printMessage(message);
      }
      await client.logout();
    } on ImapException catch (e) {
      print('IMAP failed with ${e.details}');
    }
  }
```

**Comment by robert-virkus** [comment]
`enough_mail` is not compatible with flutter web, the problem is that sockets are not supported over the web. For web environments you cannot access IMAP or POP3 servers directly.
