### ISSUE TITLE
IMAP mailbox commands returns wrong Mailbox

### ISSUE THREAD

**Issue by azulli** [Enough-Software/enough_mail#135]
Hi,
don't know if it's on purpose or a regression, but the mailbox commands of `ImapClient` returns always the current selected mailbox.

That way, if the current selected mailbox is, for example, `INBOX.recipes` and we would unsubscribe from the `INBOX.recipes.shrimps` the command is issued with the correct mailbox path, but the server response cannot be verified because the method return value will be Mailbox instance of `INBOX.recipes`.

So I'm unsure if the return value should be the passed-in Mailbox instance with the attributes updated or a simple boolean status.

Regards.

**Comment by robert-virkus** [comment]
Thanks, this does not seem right. When you unsubscribe from a box, that box should be returned and not the currently selected mailbox. I will look into this!
