### ISSUE TITLE
Rare imap response partial reading.

### ISSUE THREAD

**Issue by azulli** [Enough-Software/enough_mail#140]
Hi, I'm trying to understand an issue i'm having while fetching a bunch of emails, hoping you can shed some lights on this.
Sometimes, long responses aren't fetched entirely by `ImapResponseReader.onData()` before calling `onImapResponse()`, resulting in two type of errors:
1. the warning "some parentheses have not been closed: [ParenthizedListType.sibling]"
2. the error "no task found for command []" without the tag between the brackets

This is a typical fetch that I'm sending:
```
UID FETCH 25,19,17:18,16,15,11,14,9,3,2,1,4:5,26,6:8,10,13,12 (UID FLAGS RFC822.SIZE BODYSTRUCTURE BODY.PEEK[HEADER])
```

The following is a server response that fails often (more or less 1800 chars on the first line, I've added some wrapping for displaying purpose):
```
* 16 FETCH (UID 16 FLAGS (\Seen PEC_INBOX) RFC822.SIZE 249132 BODYSTRUCTURE
 ((("text" "plain" ("charset" "ISO-8859-1") NIL NIL "quoted-printable" 337 7 NIL NIL NIL NIL)("message" "rfc822"
 ("name" "attachmen.eml") NIL NIL "7bit" 236329 ("Mon, 2 Nov 2020 11:40:50 +0100" "other draft"
 ((NIL NIL "redacted1" "mailer.mailer.email")) ((NIL NIL "redacted1" "mailer.mailer.email")) ((NIL NIL "redacted1"
 "mailer.mailer.email")) ((NIL NIL "redacted1" "mailer.mailer.email")) NIL NIL NIL
 "<0A5A9ECB-E88A-BBD1-D179-E9E9AD34AC63@r.mailer.email>") (("text" "plain" ("charset" "utf8") NIL NIL
 "quoted-printable" 39 1 NIL NIL NIL NIL)("image" "jpeg" ("charset" "utf8" "name" "sample_7.jpg") NIL NIL
 "base64" 74858 NIL ("attachment" ("filename" "sample_7.jpg" "modification-date" "Mon, 2 Nov 2020 11:35:42 +0100"
 "size" "54704")) NIL NIL)("image" "jpeg" ("charset" "utf8" "name" "sample_6.jpg") NIL NIL "base64" 91386 NIL
 ("attachment" ("filename" "sample_6.jpg" "modification-date" "Mon, 2 Nov 2020 11:35:45 +0100" "size" "66782")) NIL
 NIL)("image" "jpeg" ("charset" "utf8" "name" "sample_5.jpg") NIL NIL "base64" 67954 NIL ("attachment" ("filename"
 "sample_5.jpg" "modification-date" "Mon, 2 Nov 2020 11:35:48 +0100" "size" "49657")) NIL NIL) "mixed" ("charset"
 "utf8" "boundary" "g9k8texkFFJunE") NIL NIL NIL) 3056 NIL ("attachment" ("filename" "attachmen.eml")) NIL
 NIL)("application" "xml" ("name" "attachme.xml") NIL NIL "7bit" 768 NIL ("attachment" ("filename" "attachme.xml"))
 NIL NIL) "mixed" ("boundary" "----=_Part_74585_74692741.1604313653949") NIL NIL NIL)("application"
 "pkcs7-signature" ("name" "smime.p7s" "smime-type" "signed-data") NIL "S/MIME Cryptographic Signature"
 "base64" 9482 NIL ("attachment" ("filename" "smime.p7s")) NIL NIL) "signed" ("protocol"
 "application/pkcs7-signature" "micalg" "sha-1" "boundary" "----=_Part_74587_349671096.1604313653951") NIL
 NIL NIL) BODY[HEADER] {1239}
$$$ HEADERS $$$
)
```

The FetchParser is feed with only the first line, without the headers and the final closing parenthesis, that are incorrectly parsed in the following stream events, causing the first error.

The latter error occurs when sometimes the initial `*` of the untagged response is missing, as for example:
```
 16 FETCH (UID 16…
```

In this case I'm not sure if it's lost in the previous stream event, between the events or somewhat the imap server forgets to add it.

I'm able to reproduce the issue by sending multiple times the fetch request on the same connection while the IDLE mode is enabled and issuing the idle done/idle start commands before and after each request. I'm also using a simple lock mechanism to avoid the requests overlapping.

Regards.

**Comment by robert-virkus** [comment]
Thanks for the report. You should (tm) not need to deploy a separate lock mechanism as `ImapClient` provides a queue mechnanism on its own. Just to clarify, this is not always happening when you request the `BODYSTRUCTURE` of the same message, right?

**Comment by robert-virkus** [comment]
Also, what IMAP server are you connected to? Could you share the server greeting (the initial response)?

**Comment by azulli** [comment]
Yes, not always the same message shows this behavior. Today consistenly is this one, in a particular mailbox.

It's a java based one, if remember correctly, but as soon I'm back in office I'll post the requested info.

**Comment by robert-virkus** [comment]
I wonder if this could be reproduced in a test-case, one part of the problem seems to be that the end of a server response is not always correctly detected. Possibly this could be tested in `uint8_list_reader_test.dart`?

**Comment by azulli** [comment]
I'm back.
I was misled, the IMAP server is in fact a dovecot instance. The response upon connection is:
`[CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ AUTH=PLAIN] Dovecot ready`

**Comment by robert-virkus** [comment]
I can reproduce this in a test case where I deliver a response across 2 onData calls with the separation between `\r` and `\n` as you have explained.
