### ISSUE TITLE
Character set problem

### ISSUE THREAD

**Issue by gmalakov** [Enough-Software/enough_mail#144]
Decoding utf8 character set causes problems. As header variable string value should be 'utf-8' not 'utf8'.
Please fix it.

**Comment by robert-virkus** [comment]
Thanks for the report, but can you explain the problem in more detail? `enough_mail` recognizes both `utf8` and `utf-8` for UTF8 in the `charset` parameter of the `content-type` header.

**Comment by gmalakov** [comment]
Ok. Well there is a function to stringify the charset. And when you send
the header like text/plain; charset=utf8(instead of utf-8). Some of the
email servers don't recognize this correctly and as a result email cannot
be read correctly


На пн, 19.04.2021 г. в 21:18 ч. Robert Virkus ***@***.***>
написа:

**Comment by robert-virkus** [comment]
Thanks for the clarification, working on it next.

**Comment by gmalakov** [comment]
I thank you.
I just have some problems implementing the last version because. Dart build
is still not null safe and depends on some arg parser old version and
logger old version and etc.
I hope they will fix that soon also.

На вт, 20.04.2021 г. в 10:18 ч. Robert Virkus ***@***.***>
написа:

**Comment by robert-virkus** [comment]
I don't have any experience with Dart Build, but in general you can mix null-safe and legacy code nowadays. So you do not need to upgrade your own project to become null-safe and still can use the null-safe versions of `enough_mail`.
