### ISSUE TITLE
A value of zero should be valid literal in ImapResponseLine

### ISSUE THREAD

**Issue by azulli** [Enough-Software/enough_mail#145]
Hi,
the check of the `isWithLiteral` getter on `ImapResponseLine` should be true even when `literal` is 0.
Case on point is a malformed multipart/alternative section of a html email in which one of the sub parts has no content, as in this example:

```
--=__boundary
Content-Type: multipart/alternative

--=__boundary
Content-Type: text/plain

--=__boundary
Content-Type: text/html

<html><body><h1>Hello there!</h1></body></html>
--=__boundary
```

Here, the text/plain part has no content (should have been "Hello there!").
Assuming that its part has id "2.1", when issuing a FETCH for retrieving this specific id, we have a response like this (omitting the non relevant parts):
```
...) BODY[2.1] {0}
```
This causes the parser to fail, unless we account for a 0 length continuation.

Regards.

**Comment by robert-virkus** [comment]
Thanks for the report, it would be great if you could test this proposed fix.
