### ISSUE TITLE
MimeMessage isTextPlainMessage fails with multipartMixed

### ISSUE THREAD

**Issue by castaway** [Enough-Software/enough_mail#149]
It seems isTextPlainMessage only passes if there is a multipartAlternative (or only text parts), if my message is multipartMixed (eg text/plain and a text/vcalender), it returns false. Is this intended? 

I'm currently using MimeMessage.parseFromText(), not any of the rest of enough_mail.

**Comment by robert-virkus** [comment]
Pushed the changed with `messageType.isMultipart` check now, thanks for the pull request and the report!
