### ISSUE TITLE
IMAP: Support APPEND command

### ISSUE THREAD

**Issue by robert-virkus** [Enough-Software/enough_mail#15]
Compare https://tools.ietf.org/html/rfc3501#section-6.3.11
The APPEND command is used for adding messages on the IMAP server.

**Comment by ali7234** [comment]
Working on the APPEND command but after the successful execution of APPEND command. Response was continuation not handled. Any idea about how to handle the continuation for storing the email?

**LOG**
```
I/flutter ( 8107): C: a5 APPEND INBOX.Sent {1000}
I/flutter ( 8107): S: + OK
I/flutter ( 8107): continuation not handled: [+ OK
I/flutter ( 8107): ]
```

**Comment by robert-virkus** [comment]
Hi Ali,

many thanks for the help. The continuation can be defined in the Command's `withContinuation` constructor, compare for example this code for `SETMETADATA`:

```dart
      // this is a complex command that requires continuation responses
      var parts = <String>[
        'SETMETADATA "${entry.mailboxName ?? ''}" (${entry.entry} {${entry.value.length}}',
        entry.valueText + ')'
      ];
      cmd = Command.withContinuation(parts);
```

The command will then handle the continuation request automatically by moving to the next command part.

**Comment by robert-virkus** [comment]
Hi Ali, I had a run and added the `appendMessage()` method in version v0.0.14
