### ISSUE TITLE
Clean up package structure

### ISSUE THREAD

**Issue by robert-virkus** [Enough-Software/enough_mail#154]
Currently the package structure is somewhat organically grown and complex for users.

-  Functionalities are spread throughout lots of different classes that can all be imported individually. It would be better to have only simple  import options, e.g. for IMAP functionalities:
  1. full package: `import 'package:enough_mail/enough_mail.dart';`
  2. IMAP-specific package: `import 'package:enough_mail/imap.dart';`
- Same goes for the documentation, which is currently fractured in the same way

Since a restructure might break current usage that depends on single imports, it might be better to implement this feature with a new major release.

**Comment by ignertic** [comment]
I see a great potential in this package so I will look at the code and try my best to open a PR!.

**Comment by robert-virkus** [comment]
Thanks, looking forward to!

An easy way would be to move everything under `lib/src` and then only keep the following files in `lib`:
* `imap.dart`, `smtp.dart`, `pop.dart` and `mime.dart`, which all export the relevant respective dart files in the `src` folder
* `enough_mail.dart` that exports `imap.dart`, `smtp.dart`, `pop.dart` and `mime.dart`

I believe in this way you  could `import 'package:enough_mail/enough_mail.dart';` for everything, but only `package:enough_mail/smtp.dart` in case you are only interested in sending email, for example.

**Comment by robert-virkus** [comment]
Note that I expect the individual APIs would need to overlap, e.g. `smtp.dart` would also export `mime.dart` since it sends MIME messages, etc. 

What are your thoughts on this, @ignertic ?

**Comment by robert-virkus** [comment]
This package structure is now updated and I appreciate any feedback, before I will release this a v2.0.0 - thanks a lot!
