### ISSUE TITLE
"utf-8" encoding continues to be "utf8" sending emails which results to unreadable text on mail hosting.

### ISSUE THREAD

**Issue by gmalakov** [Enough-Software/enough_mail#155]

**Comment by robert-virkus** [comment]
How do you reference `enough_mail` in your `pubspec.yaml`?

If you reference the GitHub repository you should be fine. The fix has not yet been released to a pubdev hosted version....

**Comment by robert-virkus** [comment]
I have now released v1.3.0 with the previous fix #144 included

**Comment by gmalakov** [comment]
Well.
That explains the situation.
Well. I just referenced as enough_mail: ^xxxx last version in the site, so
this is probably the reason.
Thank you, Robert.

На пн, 24.05.2021 г. в 23:30 ч. Robert Virkus ***@***.***>
написа:

**Comment by robert-virkus** [comment]
Assumed fixed :-)

**Comment by gmalakov** [comment]
Yes, thank you, Robert.


На вт, 25.05.2021 г. в 11:16 ч. Robert Virkus ***@***.***>
написа:
