### ISSUE TITLE
use gmail client.createMailbox have error return 

### ISSUE THREAD

**Issue by inits** [Enough-Software/enough_mail#160]
inits@QiaosMobile:~/Desktop/test/dtest$ dart run bin/dtest.dart 
mailboxes: ["INBOX" exists: 0, highestModeSequence: null, "Notes" exists: 0, highestModeSequence: null, "Qiaosb" exists: 0, highestModeSequence: null, "[Gmail]" exists: 0, highestModeSequence: null, "[Gmail]/垃圾邮件" exists: 0, highestModeSequence: null, "[Gmail]/已删除邮件" exists: 0, highestModeSequence: null, "[Gmail]/已加星标" exists: 0, highestModeSequence: null, "[Gmail]/已发邮件" exists: 0, highestModeSequence: null, "[Gmail]/所有邮件" exists: 0, highestModeSequence: null, "[Gmail]/草稿" exists: 0, highestModeSequence: null, "[Gmail]/重要" exists: 0, highestModeSequence: null, "工作邮件" exists: 0, highestModeSequence: null, "已删除的信息" exists: 0, highestModeSequence: null, "收据" exists: 0, highestModeSequence: null]
Unhandled exception:
type 'Null' is not a subtype of type 'FutureOr<Mailbox>'
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:46:41)
#1      ImapClient.onCommandResult (package:enough_mail/imap/imap_client.dart:1662:26)
#2      ImapClient.onServerResponse (package:enough_mail/imap/imap_client.dart:1638:7)
#3      ImapResponseReader.onData (package:enough_mail/src/imap/imap_response_reader.dart:37:25)
#4      ImapClient.onDataReceived (package:enough_mail/imap/imap_client.dart:213:25)
#5      ClientBase._onDataReceived (package:enough_mail/src/util/client_base.dart:122:7)
#6      _RootZone.runUnaryGuarded (dart:async/zone.dart:1546:10)
#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#8      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#9      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#10     _StreamController._add (dart:async/stream_controller.dart:607:7)
#11     _StreamController.add (dart:async/stream_controller.dart:554:5)
#12     _Socket._onData (dart:io-patch/socket_patch.dart:2160:41)
#13     _RootZone.runUnaryGuarded (dart:async/zone.dart:1546:10)
#14     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#15     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#16     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#17     _StreamController._add (dart:async/stream_controller.dart:607:7)
#18     _StreamController.add (dart:async/stream_controller.dart:554:5)
#19     _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:991:19)
#20     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#21     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395:19)
#22     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426:5)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

**Comment by robert-virkus** [comment]
Can you provide the code that you are using for creating the mailbox, ideally with the name of the mailbox?

**Comment by inits** [comment]
Future<void> imapExample() async {
  final client = ImapClient(isLogEnabled: false);
  try {
    await client.connectToServer(imapServerHost, imapServerPort,
        isSecure: isImapServerSecure);
    await client.login(userName, password);
    final mailboxes = await client.listMailboxes(recursive: true);

    print('mailboxes: $mailboxes');

    await client.createMailbox('Qiaosb22');

    // await client.logout();
  } on ImapException catch (e) {
    print('IMAP failed with $e');
  }
}

**Comment by robert-virkus** [comment]
Thanks for the additional info.
I tried creating mailboxes on several systems including Gmail and did **not** find a problem.

Just guessing from the stacktrace it seems that the folder was created but not found afterwards... Can you post the log output of the client server communication, too? 

Note that I logged into Gmail using an application password, possibly Gmail behaves differently when signing in with XOAUTH - in that case please check the scope that you are using.

**Comment by robert-virkus** [comment]
You can also try again the version v1.3.4 which resolves a similar problem when no mailbox was selected

**Comment by inits** [comment]
great that ,thanks
