### ISSUE TITLE
How to download or fetch an attachment?

### ISSUE THREAD

**Issue by xamantra** [Enough-Software/enough_mail#161]
I know that this is the function to get a list of attachment.
```dart
mimeMessage.findContentInfo(disposition: ContentDisposition.attachment)
```
But how do I actually fetch or download them? I don't see something like a *file URL*.

This is the first time I work with an email client so I have no idea.

**Comment by robert-virkus** [comment]
It depends on the state of your message. I am assuming you are using the highlevel API aka `MailClient`.

- Is the message downloaded fully, just call `mimeMessage.getPart(String fetchId)`
- Is the part not downloaded (ie the above yields `null`), then call `mailClient.fetchMessagePart(String fetchId)`

You learn the `fetchId` from the `findContentInfo()` results,  e.g.

```dart
final infos = mimeMessage.findContentInfo();
for (final info in infos) {
  MimePart? part = mimeMessage.getPart(info.fetchId);
  if (part == null) {
     part = await mailClient.fetchMessagePart(info.fetchId);
  }
  await processAttachment(part);
}
```

Please note that the above case is a bit stupid - if you want to download all attachments of a given message anyhow, just call `mailClient.fetchMessageContents()`, for example.

**Comment by xamantra** [comment]
Thank you @robert-virkus 
I'll try this tomorrow at work. just clocked out.

**Comment by xamantra** [comment]
I finally got to fetch both media and documents thanks.

But I worry about the speed because it seems 
```dart
_imapClient.fetchMessages(sequence, 'BODY.PEEK[]') // downloads the attachment in advance.
// I load 10 emails per pagination and if there's attachment to every emails it's going to be slow.
```
What should be the `fetchContentDefinition` if I don't want the attachments to download in advance?
I only want to download them when user clicks the attachment widget.

**Comment by robert-virkus** [comment]
If you don't want to learn the IMAP details I really recommend to use the high-level API aka `MailClient` instead of the low level API.

`MailClient.fetchMessages()` fetches only the message data of those messages that are within the bounds of the specified `downloadSizeLimit`. Accordingly you can specify the maximum allowed size in `MailClient.fetchMessageContents()`.

Often, you will download the ENVELOPE data first and then fetch more details later.

**Comment by robert-virkus** [comment]
See here the full documentation: https://pub.dev/documentation/enough_mail/latest/mail_mail_client/MailClient-class.html

**Comment by xamantra** [comment]
The reason I wasn't using the high-level API is because when I first tried it with our company email with correct username and password. It didn't work. So I went with low-level one.

**Comment by xamantra** [comment]
Here, I posted a new issue about high-level MailClient not working: https://github.com/Enough-Software/enough_mail/issues/162

**Comment by robert-virkus** [comment]
I think this issue can now be closed, please reopen if you need more info.
