### ISSUE TITLE
IMAP createMailbox should use a NoResponseParser internally.

### ISSUE THREAD

**Issue by azulli** [Enough-Software/enough_mail#163]
Hi,
the ImapClient.createMailbox function currently sends the IMAP "CREATE" with a NoopParser, requiring a prior mailbox selection.
A NoResponseParser could be better suited for the outcome of the command, because the IMAP command does not returns any untagged response and does not need a mailbox to operate upon.

Maybe this change can resolve also the #160.

**Comment by robert-virkus** [comment]
Thanks, that makes a lot of sense! Will do the suggested change with the next release.

**Comment by robert-virkus** [comment]
Actually, I don't think it's necessary, as the `Mailbox` parameter can be `null` for `NoopParser`.
