### ISSUE TITLE
How to get full message details with eventBus.listen

### ISSUE THREAD

**Issue by sandspoof** [Enough-Software/enough_mail#166]
Hi, I'm using 
_inboxMailClient.eventBus.on<MailLoadEvent>().listen((event) async { 
  some login goes here
}_

to listen for new incoming message, but I see that the message content is of _envelope_ type. I need the full message to come in.

Is this possible?

Any advice will be helpful.
Thanks in advance.

**Comment by robert-virkus** [comment]
Right now you would need to download the message manually, e.g. 

```dart
mailClient.eventBus.on<MailLoadEvent>().listen((loadEvent) async {
   final completeMimeMessage = await mailClient.fetchMessageContents(loadEvent.message);
});
```

Can you explain your use case in more detail? I'm surprised to learn that you want to download the full message contents of every incoming message. If I understand your use case better I might add this as an option.

**Comment by sandspoof** [comment]
Hi @robert-virkus 

Thank you for the feedback. I have learned something new.

With this app I'm saving mimeMessage data on the device as to only get new messages and not fetch all messages each time they log in (saving data usage). In order to save the message data I had to convert mimeMessage data to json and then write to a file (using the enoughMail methods), but doing that to an incoming message, which only has the envelope data, rendered all the data _null_ when retrieving the data again. That's why I needed all the message data when writing it to the device.

I ended up building my own dynamic list of message data from the mimeMessages, then converting an writing it to device, which made it easier to read the data properties and there was no data lost.

I'm still getting to know Flutter and enoughMail so this information is vital to me.

Again, thank you.

**Comment by robert-virkus** [comment]
I would want to check some conditions like WiFi conectivity before downloading  new messages fully but your general use case makes sense.

In case you haven't stumbled upoon it: convert mime message to text by calling `mimeMessage.renderMessage()` and re-construct it by calling `MimeMessage.parseFromText(String text)`.

**Comment by sandspoof** [comment]
Hi @robert-virkus 

Apologies for the late reply.

Yes you make a good point on checking the WiFi connection.

I have used those methods to convert and construct mimeMessage data. Very useful.

Thank you for the information, I'm closing this issue.
