### ISSUE TITLE
web application

### ISSUE THREAD

**Issue by Tzanou123** [Enough-Software/enough_mail#171]
Hello,

is this dependency can work in a web browser ? Because when i try to launch it in chrome with discover function it cant detect gmail settings ! when i try it in an android device it work perfectly !

**Comment by robert-virkus** [comment]
Sadly that's not possible, as the web platform does not support sockets. 
Yes, there are WebSockets, but IMAP, SMTP and POP require posix sockets, which are not available on the web.

In theory, there could be some ways how to realize web support:

1. Create a proxy service that translates from websocket <-> socket. This would, however, be a huge potential security threat, as all trafic of all web clients would go through this proxy. 
2. Use the http-based JMAP and a JMAP compliant email service. Drawbackis that there are only very few JMAP compliant email services out there so far, afaik.
3. Use Google and Microsoft-proprietary REST-based APIs (Gmail API / Microsoft Graph). Drawback is that these APIs are not standardized, can change ad hoc and are only served by the big players.

Does this help? Any other ideas?

**Comment by Tzanou123** [comment]
Thanks dude for your response !

That's sad we really need to use the imap protocol. 

I was trying it with gmail but in final i have my own imap server to call and i want my app  can be build for ios, android, web browser and binary ! 

So if i understand well there is no way actually with flutter to communicate with an imap server in a web browser ?

**Comment by robert-virkus** [comment]
This is not a limitation of Flutter, this is a limitation of the web. Any web app needs a proxy to communicate via IMAP / Sockets.

If you only want to create a web client for your own IMAP service, you could use `enough_mail` on the [server side](https://dart.dev/server), add a restful- or gRPC API and call that API from your Flutter-based web app. Check out [Conduit](https://pub.dev/packages/conduit) as a server side Dart framework, for example.

**Comment by Tzanou123** [comment]
Ok thank you,
I was trying to use a proxy  to make it work ! I m using https://github.com/novnc/websockify who seem to make what we need
But when i try to call the proxy with your Low level IMAP API usage example (client.connectToServer) ! The proxy don t seem to be called ! if i try to call the proxy via telnet i get a response from the proxy !
I maybe forgot something ! Or may i need to change some code in your dependencies ?

**Comment by robert-virkus** [comment]
Not sure how your setup is. The way it could work on the web would be like this (I think!):

- you have a web app that uses a (new, to be written) API for communicating with your server, e.g. via HTTP REST calls or via WebSockets
- your server app then translates the requests to the corresponding IMAP etc calls. Your server app can use the `enough_mail` package, assuming it is written in Dart.

For me it seems that you try to create a TCP/IP socket in your web app (indirectly as you seem to be using enough_mail in your web app). As the web does not support generic TCP/IP sockets, this cannot work.

**Comment by robert-virkus** [comment]
Closing this as this is out of scope for this package.
