### ISSUE TITLE
Error: The setter 'messagesRecent' isn't defined for the class 'Mailbox'

### ISSUE THREAD

**Issue by chalwe1997** [Enough-Software/enough_mail#175]
hi, when i try running my app iam getting this error
          ^^^^^^^^^^^^^^
: Error: The setter 'messagesRecent' isn't defined for the class 'Mailbox'.
../…/imap/status_parser.dart:38
- 'Mailbox' is from 'package:enough_mail/imap/mailbox.dart' ('../../../flutter/.pub-cache/hosted/pub.dartlang.org/enough_mail-1.3.6/lib/imap/mailbox.dart').
package:enough_mail/imap/mailbox.dart:1
Try correcting the name to the name of an existing setter, or defining a setter or field named 'messagesRecent'.
            box.messagesRecent = value;
                ^^^^^^^^^^^^^^

**Comment by robert-virkus** [comment]
fixed in 2.0.0
