### ISSUE TITLE
continuation not handled

### ISSUE THREAD

**Issue by ShadmanAfzal** [Enough-Software/enough_mail#177]
Whenever, i try to fetchMessages after authenticating user via Flutter_Web_Auth, i am getting this error. I am getting this message on terminalA: continuation not handled: [+ eyJzdGF0dXMiOiI0MDAiLCJzY2hlbWVzIjoiQmVhcmVyIiwic2NvcGUiOiJodHRwczovL21haWwuZ29vZ2xlLmNvbS8ifQ==] but the Flutter_Web_Auth is working fine as it is giving me the access token.

But if i use googleSignin for authentication, I am able to get the messages successfully.

Here's  my code.

Future<String> authenticate() async {
    final url = Uri.https('accounts.google.com', '/o/oauth2/v2/auth', {
      'response_type': 'code',
      'client_id': googlelientId,
      'redirect_uri': '$callbackUrl:/',
      'scope': 'email',
    });

    final result = await FlutterWebAuth.authenticate(
        url: url.toString(), callbackUrlScheme: callbackUrl);

    final code = Uri.parse(result).queryParameters['code'];

    final response = await http.post(
      Uri.parse('https://oauth2.googleapis.com/token'),
      body: {
        'client_id': googlelientId,
        'redirect_uri': '$callbackUrl:/',
        'grant_type': 'authorization_code',
        'code': code,
      },
    );

    final accessToken = jsonDecode(response.body)['access_token'] as String;
    return accessToken;
  }

getMails() async {
    final token = await authenticate();
    await client.connectToServer("imap.gmail.com", 993, isSecure: true);
    await client.authenticateWithOAuthBearer(widget.email, token);

    OauthAuthentication _mailAuth = OauthAuthentication(
      widget.email,
      token,
    );

    MailAccount mailAccount = MailAccount.fromManualSettingsWithAuth(
      "gmail.com",
      widget.email,
      "imap.gmail.com",
      "smtp.gmail.com",
      _mailAuth,
    );

    mailClient = MailClient(
      mailAccount,
      logName: mailAccount.name,
    );

    await mailClient.connect();

    Mailbox inbox = await mailClient.selectInbox();

    final fetchResult = await mailClient.fetchMessages();
    for (MimeMessage msg in fetchResult) {
      print(msg.decodeSubject());
    }
  }

## Please note that the logic is fine with googlesignin

**Comment by robert-virkus** [comment]
Sorry for the late response. I am also using the `flutter_web_auth` plugin, I noticed that my scope is different from yours and apparently also how I further process the token. Possibly this code helps:
```dart
    // Construct the url
    final uri = Uri.https('accounts.google.com', '/o/oauth2/v2/auth', {
      'response_type': 'code',
      'client_id': clientId,
      'redirect_uri': '$callbackUrlScheme:/',
      'scope': 'https://mail.google.com/',
      'login_hint': email,
    });

    // Present the dialog to the user
    final result = await FlutterWebAuth.authenticate(
        url: uri.toString(), callbackUrlScheme: callbackUrlScheme);

    // Extract code from resulting url
    final code = Uri.parse(result).queryParameters['code'];

    // Use this code to get an access token
    final response = await HttpHelper.httpPost(
        'https://oauth2.googleapis.com/token',
        body: {
          'client_id': clientId,
          'redirect_uri': '$callbackUrlScheme:/',
          'grant_type': 'authorization_code',
          'code': code,
        });

    // Get the access token from the response
    return OauthToken.fromText(response.text!);
```

**Comment by ShadmanAfzal** [comment]
ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MailException: TimeoutException after 0:00:10.000000: Future not completed
E/flutter (25171): TimeoutException after 0:00:10.000000: Future not completed
E/flutter (25171):
E/flutter (25171): #0      _OutgoingSmtpClient._connectOutgoingIfRequired
package:enough_mail/…/mail/mail_client.dart:2717
E/flutter (25171): <asynchronous suspension>
E/flutter (25171): #1      _OutgoingSmtpClient.sendMessage
package:enough_mail/…/mail/mail_client.dart:2730
E/flutter (25171): <asynchronous suspension>
E/flutter (25171): #2      MailClient._sendMessageViaOutgoing
package:enough_mail/…/mail/mail_client.dart:703

**Comment by robert-virkus** [comment]
Can you check again? This works fine for me with outlook.

**Comment by robert-virkus** [comment]
Seems to work now.
