### ISSUE TITLE
How to delete an email permanently

### ISSUE THREAD

**Issue by ShadmanAfzal** [Enough-Software/enough_mail#178]

**Comment by robert-virkus** [comment]
`MailClient` has now the optional expunge boolean parameter:
`Future<DeleteResult> deleteMessages( MessageSequence sequence, {bool expunge = false})`

**Comment by robert-virkus** [comment]
Mark the messages as deleted and then expunge.
```dart
await _imapClient.store(sequence, [MessageFlags.deleted], action: StoreAction.add, silent: true);
await _imapClient.expunge();
```
