### ISSUE TITLE
Date Codec not working as expected for timezones behind UTC

### ISSUE THREAD

**Issue by matthiasn** [Enough-Software/enough_mail#182]
This library worked perfectly well for me in Berlin but started failing after I traveling to Central America this week, so into a timezone behind UTC.

After some debugging, I found that the header in an IMAP message created by this library was incorrect, for example in the raw source in Apple Mail:

![image](https://user-images.githubusercontent.com/1390808/148630780-f8d3856a-cd82-4d59-8279-be0e8e2d3355.png)

Here, I would have expected `Fri, 07 Jan 2022 20:56:34 -0500` instead.

**Comment by matthiasn** [comment]
Suggested fix in #181. Thanks for this library!

**Comment by robert-virkus** [comment]
Thanks a lot for your work, your important fix is now merged. 
I will try to release a new version soon.
