### ISSUE TITLE
ignoring response starting with [Return-Path: <sales@yarsort.com.ua>] with 1 lines.

### ISSUE THREAD

**Issue by yarsort** [Enough-Software/enough_mail#190]
What is this message?

**Comment by robert-virkus** [comment]
It seems that you are connecting to a POP mail service, can you provide some more details, specifically the log entries above and below the entry?
If necessary, please turn on logging by setting `isLogEnabled` to `true` in the constructor, e.g. `PopClient(isLogEnabled: true, logName: 'myPopService');`.

**Comment by yarsort** [comment]
I found. My POP3 server returned LIST '+OK 20 Messages' and it's no simple '+OK'.

`/// Parses list responses
class PopListParser extends PopResponseParser<List<MessageListing>> {
  @override
  PopResponse<List<MessageListing>> parse(List<String> responseLines) {
    final response = PopResponse<List<MessageListing>>();
    parseOkStatus(responseLines, response);
    if (response.isOkStatus) {
      final result = <MessageListing>[];
      response.result = result;
      for (final line in responseLines) {
        if (line.contains('+OK')) {
          continue;
        }
        final parts = line.split(' ');
        final MessageListing listing;
        if (parts.length == 2) {
          listing = MessageListing(
              id: int.parse(parts[0]), sizeInBytes: int.parse(parts[1]));
        } else if (parts.length == 3) {
          // eg '+OK 123 123231'
          listing = MessageListing(
              id: int.parse(parts[1]), sizeInBytes: int.parse(parts[2]));
        } else {
          throw FormatException('Unexpected LIST response line [$line]');
        }
        result.add(listing);
      }
    }
    return response;
  }
}`

**Comment by yarsort** [comment]
Please replace this sample of code... From "==" to "contains" in expression

**Comment by robert-virkus** [comment]
Thanks a lot for your contribution - do you know about [pull requests](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request)? In the future you can suggest changes via PRs and so your contribution would be official :-)
