### ISSUE TITLE
How add *.zip file into message and issue with SMTP auth

### ISSUE THREAD

**Issue by yarsort** [Enough-Software/enough_mail#192]
Hello again. :)

I have one problem; i added *.zip attachment, but i don;t see this file in my letter on e-mail server. How correctly add attachment into message? My code in screenshot...

Issues in SMTP auth: 

incorrect in your example: 
await client.login('user name', 'user password');

correct in my example:
await client.authenticate('user name', 'user password');

![изображение](https://user-images.githubusercontent.com/54131603/169645608-eb53eb1d-4a3e-4598-b978-b1c7d48ab1db.png)

**Comment by yarsort** [comment]
Maybe, rename this function: 'authenticate' to 'login' or 'login' in pop3 module to 'authenticate'... I don't know...

**Comment by yarsort** [comment]
I found! I forgot add word 'await' before adding file into attachments... ;)

![изображение](https://user-images.githubusercontent.com/54131603/169648863-9bd9b242-4eeb-4f68-bc3e-86dfa44763cd.png)

**Comment by yarsort** [comment]
Please add to your example in pub.dev this adding files in attachments. It's will be good for developers. Thank you.

**Comment by robert-virkus** [comment]
Thanks for the suggestion, added a file attachment example in the v2.0.1 release
