### ISSUE TITLE
MessageBuilder replace pre content when add new Text, HTML or File....

### ISSUE THREAD

**Issue by lqmminh** [Enough-Software/enough_mail#193]
final builder = MessageBuilder.prepareMultipartAlternativeMessage()
        ..from = [MailAddress('My name', 'minh1@xxx.com')]
        ..to = [MailAddress('Your name', 'minh2@xxx.com')]
        ..subject = 'My first message'
        ..addTextPlain('hello world.')
        ..addTextHtml('<p>hello <b>world</b></p>');
      final file = File(xfile.path);
      await builder.addFile(file, MediaSubtype.imageJpeg.mediaType);
      await builder.addTextPlain('hello world2');
      final mimeMessage = builder.buildMimeMessage();
      final sendResponse = await client.sendMessage(mimeMessage);
      
      With code above, in minh2@xxx.com just see: hello world2
      don't have pre text, html and image file

**Comment by lqmminh** [comment]
So, Do you know how we can add multi images and text?

**Comment by lqmminh** [comment]
> I noticed that you add the `text/plain` part twice. If you want to update that part, you can use code like this to update it:
> 
> ```dart
> final partBuilder = builder.getTextPlainPart();
> if (partBuilder != null) {
>   partBuilder.text = text;
> } else {
>   builder.addTextPlain(text);
> }
> ```
> 
> Does this solve you problem?

Thanks but it can't solve my problem

**Comment by lqmminh** [comment]
Wow, Thanks I will try
You need write it in example 👯

**Comment by lqmminh** [comment]
Hi I don't work, you can try it at your side?

**Comment by lqmminh** [comment]
final builder = MessageBuilder()
        ..from = [MailAddress('Personal Name', 'sender@domain.com')]
        ..to = [
          MailAddress('Recipient Personal Name', 'minh@xxx.com'),
          // MailAddress('Other Recipient', 'other@domain.com')
        ]
        ..addMultipartAlternative(
          plainText: 'Hello world  plain text!',
          htmlText: '<p>Hello world html text!</p>',
        );
      final file = File(xfile.path);
      await builder.addFile(file, MediaSubtype.imageJpeg.mediaType);

      final sendResponse = await client.sendMessage(builder.buildMimeMessage());
      
      With new version, i updated same your example, and now it can sent html + image file, not have text: "Hello world  plain text". it's normally?

**Comment by robert-virkus** [comment]
Hi, yes that's expected. `multipart/alternative` means that you have two version of the same thing and each viewer displays the content part that it can display best. E.g. a command line mailer would show the plain text part while most other mail apps would choose to display the html part.

**Comment by lqmminh** [comment]
Yes okay, thank you!
