### ISSUE TITLE
crypto dependency constraints

### ISSUE THREAD

**Issue by hpoul** [Enough-Software/enough_mail#194]
Hello,
I think it would be nice to have a bit looser dependency constraints. I don't think there is a reason to depend on crypto >= 3.0.2 instead of just 3.0.0. This breaks my dependencies due to `integration_test` requiring crypto 3.0.1

```
Because every version of integration_test from sdk depends on crypto 3.0.1 and enough_mail >=2.0.0 depends on crypto ^3.0.2, integration_test from sdk is incompatible with enough_mail >=2.0.0.
So, because authpass depends on both enough_mail ^2.1.0 and integration_test from sdk, version solving failed.
pub finished with exit code 1
```

I would suggest simply depending on the minimal version of a dependency which is required, instead always on the latest, this makes updating libraries for apps far easier as it can be done one by one.. For now i'll simply use a `dependency_overrides`, but it would be nice in the future to keep this in mind.

thanks,
  Herbert

**Comment by robert-virkus** [comment]
thanks for the useful suggestion, fixed in v2.1.1 :-)
