### ISSUE TITLE
add Content-ID on attachments with low level smtp api

### ISSUE THREAD

**Issue by Tzanou123** [Enough-Software/enough_mail#201]
Hello,

Is there any way to add and customize a Content-ID on attachments with low level smtp api ?

I need it to make a reference on an <img> tag in my html

i actually use `await builder.addFile(file, MediaSubtype.imageJpeg.mediaType);`

Thanks

**Comment by robert-virkus** [comment]
I believe you can achieve your goal using this code:
```dart
final partBuilder = await builder.addFile(file, MediaSubtype.imageJpeg.mediaType);
partBuilder.addHeader('Content-Id', 'yourUniqueIdHere');
```

**Comment by Tzanou123** [comment]
Thanks dude !
