### ISSUE TITLE
more SMTP example

### ISSUE THREAD

**Issue by Jefry-nolastname** [Enough-Software/enough_mail#21]
hello, first of all thanks for creating this plugin. To my knowledge this is the first plugin that combine SMTP and IMAP in one plugin. I'm somewhat new in programming world and i'm working on a project that need this plugin. can you please provide simple example how can i use the SMTP client to connect->login-> sendMSG. thank you so much.

**Comment by Jefry-nolastname** [comment]
"sorry for the stupid question but how do you prepare the mimemessage to be used in function sendMessage?"

final message = MimeMessage()
      ..from.add(Address('xxxxx@xxxxx.xx.xx'))
      ..recipients.add(recipient)
      ..attachments.addAll(filesAttachment)
//      ..ccRecipients.addAll(['destCc1@example.com', 'destCc2@example.com'])
//      ..bccRecipients.add(Address('bccAddress@example.com'))
      ..subject = subject
//      ..html = "<h1>Test</h1>\n<p>Hey! Here's some HTML content</p>"
      ..text = body;

**Comment by robert-virkus** [comment]
In the meantime (v0.0.9) there is the MessageBuilder class that helps you creating new mime messages, including adding files:
```dart
var client = SmtpClient('enough.de', isLogEnabled: false);
  await client.connectToServer('smtp.domain.com', 465, isSecure: true);
  var loginResponse = await client.login('user.name', 'password');
  if (loginResponse.isOkStatus) {
    var builder = MessageBuilder.prepareMultipartAlternativeMessage();
    builder.from = [MailAddress('My name', 'sender@domain.com')];
    builder.to = [MailAddress('Your name', 'recipient@domain.com')];
    builder.subject = 'My first message';
    builder.addPlainText('hello world.');
    builder.addHtmlText('<p>hello <b>world</b></p>');
    var mimeMessage = builder.buildMimeMessage();
    var sendResponse = await client.sendMessage(mimeMessage);
    print('message sent: ${sendResponse.isFailedStatus}');
  }
```
Compare *message_builder_test.dart* for more examples.
