### ISSUE TITLE
Unknown feature REQUESTED_WITH_HEADER_CONTROLE

### ISSUE THREAD

**Issue by Agbeniga** [Enough-Software/enough_mail#218]
When trying to view the details of a message, 
`java.lang.RuntimeException:` Unknown feature REQUESTED_WITH_HEADER_CONTROLE/MethodChannel#flutter/platform_views( 8063):  at `androidx.webkit.internal.WebViewFeatureInternal.isSupported(WebViewFeatureInternal.java:574)` is thrown.

![image](https://user-images.githubusercontent.com/38624784/227391704-6489f545-020d-420a-a273-17ace53d4f36.png)
![image](https://user-images.githubusercontent.com/38624784/227391783-bf57b7e8-5d0e-4db0-963d-3a2611b8e33d.png)

**Comment by robert-virkus** [comment]
This does not seem to be a problem of this library but instead of the used webview implementation
