### ISSUE TITLE
Error: A value of type 'List<int>' can't be assigned to a variable of type 'Uint8List'.

### ISSUE THREAD

**Issue by Entrebear** [Enough-Software/enough_mail#224]
Hi

I am on the beta channel of Flutter (Flutter 3.15.0-15.1.pre • channel beta • https://github.com/flutter/flutter.git, Framework • revision b2ec15bfa3 (6 days ago) • 2023-09-14 15:31:44 -0500, Engine • revision 5c86194494, Tools • Dart 3.2.0 (build 3.2.0-134.1.beta) • DevTools 2.27.0) and I received the following error:

~/AppData/Local/Pub/Cache/hosted/pub.dev/enough_mail-2.1.1/lib/src/private/smtp/commands/smtp_auth_cram_md5_command.dart:50:33: Error: A value of type 'List<int>' can't be assigned to a variable of type 'Uint8List'.
 - 'List' is from 'dart:core'.
 - 'Uint8List' is from 'dart:typed_data'.
      password = passwordDigest.bytes;
                                ^
Target kernel_snapshot failed: Exception

I am also facing conflicts as enough_mail doesn't support the latest version of intl which leads to conflicts with other packages.

Please can you update to resolve these issues.

**Comment by gmalakov** [comment]
It just must be Uint8List.fromList(passwordDigest.bytes);
Because utf8.encode(xxxx) now gives UInt8List.
I've changed here and it works as charm.

**Comment by robert-virkus** [comment]
Thanks a lot guys!
I wonder how this change could be release so that compatibility with older Flutter versions is not broken. Any ideas? Should this be released as a new major versionm, perhaps?

**Comment by robert-virkus** [comment]
Never mind - the change _is_ compatible with prior versions of Flutter. Thanks a bunch!

**Comment by robert-virkus** [comment]
Released as v2.1.5
