### ISSUE TITLE
MailClient.listMailboxesAsTree() with a non default pathSeparator

### ISSUE THREAD

**Issue by nruzzu** [Enough-Software/enough_mail#226]
Hello,

i'm struggling with getting the tree of my Mailboxes correctly aligned. The setup is a dovecot imap server that uses '.' as pathSeparator. The `Tree` that i receive consists of the root and all other Mailboxes as direct child of the root. It is obvious that the path splitting doesn't work as intended. I stepped through the `ListParser` and found that she correctly identifies the `pathSeparator` and writes it into the MailBox. But i found than that `MailClient.listMailboxesAsTree()` uses the `Account.incoming.pathSeparator` to split the paths. 

When i understand the code correctly the `Account.incoming.pathSeparator` is initialized with its default values '/' no matter how you instantiate a `MailAccount`. Later it can be read but not written to and in the end `listMailboxesAsTree()` uses '/' as pathSeparator though the `listMailboxes()` method has correctly determined that the pathSeparator is different.

Do i overlook something? I create the `MailAccount` from `MailAccount.fromManualSettings(...)` and put it into a `MailClient`.

My first reflex was to use the pathSeparator from the first `Mailbox` in the list because i don't expect that different Mailboxes of a `MailClient` have a different pathSeparator. This has the advantage that the pathSeparator is delivered from the imap server at runtime and not by a configuration.

**Comment by robert-virkus** [comment]
Thanks for your PR, I have also made sure to update the MailAccount.incoming.pathSeparator.
Released in v2.1.3
