### ISSUE TITLE
Convert Fetched Data to UTF-8 Charset

### ISSUE THREAD

**Issue by komnatadeveloper** [Enough-Software/enough_mail#23]
Hello.

I couldnt manage handling fetched data.

I need to convert data to UTF-8 Charset, as soon as not everybody uses English Characters.

If there is a pattern which I couldn't find, please tell.

**Comment by robert-virkus** [comment]
Thanks for testing, I just release v0.0.7 which handles content encodings much better.

Example use case:
```
var fetchResponse = await imapClient.fetchMessages(1, 10, 'BODY.PEEK[]');
var messages = fetchResponse.result;
for (var message in messages) {
   message.parse();
   // this is only for simple message, multiple parts need to be accessed individually:
   print(message.decodeContentText());
}
```

Please let me know if this works better for your usecase.

**Comment by robert-virkus** [comment]
Assumed to be fixed now.
