### ISSUE TITLE
Imap: selectMailboxByPath result null

### ISSUE THREAD

**Issue by ali7234** [Enough-Software/enough_mail#26]
It works well when pass the folder name INBOX, but when pass the other folder names like SENT, OUTBOX, method returns the result null.

`var listResponse=await client.selectMailboxByPath("SENT");`

**Comment by robert-virkus** [comment]
This seems to have been resolved by itself, please let me know what resolved your problem. 

You can also list all folders with `listMailboxes`:
 ```dart
var response = await imapClient.listMailboxes(recursive: true);
if (response.isSuccessStatus) {
  var folders = response.result;
  for (var folder in folders) {
      print(folder);
  }
}
```

**Comment by ali7234** [comment]
> 
> 
> This seems to have been resolved by itself, please let me know what resolved your problem.
> 
> You can also list all folders with `listMailboxes`:
> 
> ```dart
> var response = await imapClient.listMailboxes(recursive: true);
> if (response.isOkStatus) {
>  var folders = response.result;
>  for (var folder in folders) {
>      print(folder);
>  }
> }
> ```

Actually, On Server format of the path is "INBOX.Sent". I am just sending the "SENT". For Resolution, I fetch all the Mailboxes as just you mentioned. Then pass the folder.path to the selectMailboxByPath function.

**Code**
`var response=await client.selectMailboxByPath(folder.path);`

**Comment by robert-virkus** [comment]
ok, thanks for the clarification!
