### ISSUE TITLE
MIME/SMTP: Attachment Names

### ISSUE THREAD

**Issue by ali7234** [Enough-Software/enough_mail#29]
When I send the mail with the attachment from enough_mail smtp client. Email send successfully to the recipient but when try to fetch the file name with the above code, attribute was called on null. But, when I send mail from Outlook or other client, the above code works fine.

**Code** 
```
mimeMessage.body.structures.first.attributes.first.value
```

**Email Send Code**
```
var builder = MessageBuilder.prepareMultipartMixedMessage();
      builder.from = [MailAddress('Sender', 'sender@xyz.com')];
      builder.to = [MailAddress('Receiver', 'receiver@xyz.com')];
      builder.subject = "Test Email Attachments";
      builder.addPlainText("Test Email Attachments");
      attachments.forEach((f) {
        await builder.addFile(f.file, MediaType.fromText('application/pdf'));
      });
      var mimeMessage = builder.buildMimeMessage();
      var sendResponse = await client.sendMessage(mimeMessage);
      print('message sent: ${sendResponse.isFailedStatus}');
```

**Comment by ali7234** [comment]
Any update or workaround to resolve the attachment name issue.

**Comment by robert-virkus** [comment]
Hi Ali,

what kind of attribute do you want to read? I have noticed that some mailer provide the `name` parameter in the `Content-Type` header. Currently the MessageBuilder does not that and only specifies the `filename` parameter in the `Content-Disposition` header. So maybe adding this would help you, but I am unsure what your need is.

Best,  Robert

**Comment by ali7234** [comment]
Actually, I want to fetch the attachments from the email and show them to the user. Currently, I fetch the body of the email by using the **fetchMessagesByCriteria('1 (BODY)')**. Then, iterate through the structure object and check if there is any attachment in the mail. If, there is any attachment then I get the attachment name through **attribute** object.  But, the problem is when I send the mail through this package, and try to fetch the attachment name as mentioned above, the attribute object is null.

**Fetch Email Body**  
```
var fetchResponse = await S.sImapClient.fetchMessagesByCriteria('$sequenceID (BODY)');
```
**Attachments**

```
mimeMessage = await EmailRepository.fetchEmailBody(mailContent.emailID);

    if (mimeMessage != null) {
      mimeMessage.body.structures.forEach((f) {
        print("fetchResponse.details ${f.type} ${f.subtype} ${f.encoding}");

        if (f.type != "text" && f.type != "model" && f.type != "multipart" && f.type != "message" && f.type != "font") {
          //For File Name and Type
            List<String> name = f.attributes.first.value.split('.');
            attachments.add(FileModel(fileName: f.attributes.first.value, fileType: name[name.length - 1]));
      
        }
      });
```
If there is any issue for fetching the attachments, Please guide me to resolve the error.

**Comment by robert-virkus** [comment]
Hi Ali, thanks for the detailed descripion. Please check if version v0.0.16 resolves your problem. Now the `name` parameter is set within the `Content-Type` header as well.

A message with one `text/plain` and one `image.jpg` part previously created such a response:
```
C:  a3 UID FETCH 177 (BODY)
S: * 68 FETCH (UID 177 BODY (("text" "plain" ("charset" "utf8") NIL NIL "8bit" 45 3)("image" "jpg" ("charset" "utf8") NIL NIL "base64" 18324) "mixed"))
S: a3 OK Fetch completed (0.001 + 0.000 secs).
```
Note the `NIL` parts within the `image/jpg` response part.

With v0.0.16, the request now provides more details:

```
C:  a3 UID FETCH 177 (BODY)
S: * 68 FETCH (UID 177 BODY (("text" "plain" ("charset" "utf8") NIL NIL "8bit" 45 3)("image" "jpg" ("charset" "utf8" "name" "testimage.jpg") NIL NIL "base64" 18324) "mixed"))
S: a3 OK Fetch completed (0.001 + 0.000 secs).
```

So I do hope this fixes your problem - can you confirm?

**Comment by ali7234** [comment]
Thanks, Issue Resolved

**Comment by robert-virkus** [comment]
Nice, thanks for the confirmation!
