### ISSUE TITLE
SMTP: Connecting to gmail not working

### ISSUE THREAD

**Issue by McCrafterIV** [Enough-Software/enough_mail#30]
Hey,

it possibly a stupid error, but I can't figure out why I can't connect to the gmail smtp server using the following lines:
```
var client = SmtpClient('gmail.com', isLogEnabled: false);
await client.connectToServer('smtp.gmail.com', 465, isSecure: true);
```

It fails with the following error:
```
Unhandled Exception: SocketException: OS Error: Connection timed out, errno = 110, address = smtp.gmail.com, port = 44852
```

Thanks for feedback

**Comment by robert-virkus** [comment]
You should not use a google-owned domain but rather your own domain when creating up the SMTP client, I use `enough.de` in this example:
```
var client = SmtpClient('enough.de', isLogEnabled: true);
await client.ehlo();
var loginResponse = await client.login('user.name', 'password');
if (loginResponse.isOkStatus) {
...
}
```

Also remember that you need to set up application-specific passwords for Gmail as Oauth-based authentication is not yet supported.

The above code should create log output similar to the following:
```
connecting to server smtp.gmail.com:465 - secure: true
S: 220 smtp.gmail.com ESMTP f7sm17776845wrt.10 - gsmtp
S:
C: EHLO enough.de
S: 250-smtp.gmail.com at your service, [2003:f5:ff1f:6000:ec8d:dc31:e544:e577]
S: 250-SIZE 35882577
S: 250-8BITMIME
S: 250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH
S: 250-ENHANCEDSTATUSCODES
S: 250-PIPELINING
S: 250-CHUNKING
S: 250 SMTPUTF8
S:
C: AUTH PLAIN <base64 code scrambled>
```

Hope this helps,
yours
   Robert

**Comment by McCrafterIV** [comment]
Thanks for your help Robert,

but when I want to sent a mail via a gmail account, I have to use the `gmail.com` domain, right?

**Comment by robert-virkus** [comment]
Hi, yes, in the `connectToServer()` call you will have to specify the `smtp.gmail.com` domain. I have adapted the above example to also include that very important line. 

In the SMTP client's constructor you specify the client-side domain, this is for identifying your client against the SMTP service, which is mandatory according to the SMTP specs.

If everything is clear, please close this issue.

thanks, 
yours Robert

**Comment by McCrafterIV** [comment]
Thank you for your help. It works now for me :)
