### ISSUE TITLE
How use idleStart? 

### ISSUE THREAD

**Issue by cjamcu** [Enough-Software/enough_mail#31]
How can use listener when arrived new mails?. I see in log when arrived mails but haven't callback. Help me to implementation idle Start correctly.

**Comment by robert-virkus** [comment]
Hey Carlos, thanks for testing enough_mail! 

You need to listen for events using the `ImapClient.eventBus`. In the following I assume that you are interested in new messages.

```dart
imapClient.eventBus.on<ImapEvent>().listen(_onImapEvent);
```

When you start the IDLE mode, do not wait for its return.
I you are using the pedantic library (which I highly recommend), call `idleStart()` like this:
```dart
import 'package:pedantic/pedantic.dart';
[...]
unawaited(imapClient.idleStart());
```
If you are not using pedantic, then just do not wait for the future:
```dart
imapClient.idleStart();
```

When you receive either an `EXISTS` or a `FETCH` event, you have to stop the idle mode, fetch your message and go back into the idle mode:

```dart
void _onImapEvent(ImapEvent event) async {
    int messageSequenceId;
    if (event is ImapFetchEvent) {
      messageSequenceId = event.messageSequenceId;
    } else if (event is ImapMessagesExistEvent) {
      messageSequenceId = event.newMessagesExists;
    }
    if (messageSequenceId != null) {
      imapClient.idleDone();
      var fetchContents =
          '(BODY.PEEK[HEADER.FIELDS (message-Id references subject from to cc date content-type content-transfer-encoding)])';
      var fetchHeaderResponse =
          await imapClient.fetchMessages(messageSequenceId, -1, fetchContents);
      if (fetchHeaderResponse.isOkStatus) {
        var allMessages = fetchHeaderResponse.result;
        for (var mimeMessage in allMessages) {
          print('got new message ${mimeMessage.decodeSubject()}');
        }
      }
      unawaited(imapClient.idleStart());
    }
  }
```

Hope this helps,
yours
  Robert

**Comment by cjamcu** [comment]
Thank you very much for answering, I am trying to adjust this to my case but now every time I do the fetchMessage it gives an error. Can you help me see what is happening or help to add this to the example that is on github.

Again thank you very much.
![2020-05-02 06 08 55](https://user-images.githubusercontent.com/42654354/80862545-8a54e500-8c3b-11ea-8a24-4e4416e4a4af.jpg)

**Comment by robert-virkus** [comment]
Hi Carlos, have you been able to fetch messages before? Please turn on verbose logging by creating an `ImapClient` with the following code:
```dart
var imapClient = ImapClient(isLogEnabled: true);
```

In the log you should now see all client and server messages in more detail.

It seems to be me that the imap server is not understanding the fetch command, maybe you need to play with the `fetchContents` definition.

If you can solve it by yourself, please post the solution - and if not please post the log output.

**Comment by robert-virkus** [comment]
The high level `MailClient` API now also shows how to use `IDLE`
