### ISSUE TITLE
retrieve date

### ISSUE THREAD

**Issue by studiozocaro** [Enough-Software/enough_mail#36]
I have a problem internalDate and date is null

message.internalDate

flutter: S: a3 OK Success
flutter:  internalDate: null
flutter:  internalDate: null
flutter:  internalDate: null
flutter:  internalDate: null
flutter:  internalDate: null
flutter:  internalDate: null
flutter:  internalDate: null
flutter:  internalDate: null
flutter:  internalDate: null
flutter:  internalDate: null
flutter:  internalDate: null

**Comment by ali7234** [comment]
I also face the same issue but I found the workaround to get the date.

**Code**
```
var fetchResponse= await fetchMessagesByCriteria('$start:$end (BODY.PEEK[HEADER])');
if (fetchResponse.isOkStatus) {
  for (var message in fetchResponse.result) {
     print("Date ${message.getHeader("date").first.value}");
  }
}
```

**Comment by studiozocaro** [comment]
thanks

**Comment by robert-virkus** [comment]
The fields `date` and `internalDate` are only populated when a `Body` is fetched. Please note that this part of the API will be changed.
Once you either have fetched the header with `(BODY[HEADER])` or the full body with `(BODY[])` you can also use the the `MimeMessage.decodeHeaderDate('Date')` method, which will get you a `DateTime` object.
