### ISSUE TITLE
BODYSTRUCTURE: contentDisposition always null

### ISSUE THREAD

**Issue by ali7234** [Enough-Software/enough_mail#47]
**contentDisposition** always null, even if there is an attachments in the email.

**Code**
```
var fetchResponse = await S.sImapClient.fetchMessagesByCriteria('$sequenceID (BODYSTRUCTURE BODY.PEEK[])');
print(fetchResponse.result.first.body.structures.first.contentDisposition);
```

**Comment by robert-virkus** [comment]
Please upgrade to v0.0.18, this should fix the problems. Please note the API changes when accessing the MimeMessage.body element, this is now close to the normal MimeMessage API. Compare https://pub.dev/documentation/enough_mail/latest/mime_message/BodyPart-class.html for details.

When the problems are fixed for you, please close this bug.

**Comment by ali7234** [comment]
Issue Resolved, Thanks
