### ISSUE TITLE
IMAP EVENTS: ImapMessagesRecentEvent ImapMessagesExistEvent not working

### ISSUE THREAD

**Issue by ali7234** [Enough-Software/enough_mail#51]
Need some documentation to understand how these two listeners work. I just add the ImapMessagesRecentEvent listener to listen for the new email, and send the email to the client(user). But the listener not listen the new email message.

**Code**
```
S.sImapClient.eventBus.on<ImapMessagesRecentEvent>().listen((event) {
      print("event.eventType ${event.eventType} ${event.newMessagesRecent} ${event.oldMessagesRecent}");
    });
```

**Comment by robert-virkus** [comment]
Does #31 help you?

**Comment by robert-virkus** [comment]
Note that on low level there are several events that can be triggered:
* fetch
* exists
* recent

I haven't encountered a server that updates recent but not exists, so you can proabably just listen for exists and fetch. Also compare the event handling in the new high level MailClient.
