### ISSUE TITLE
Bug change folder

### ISSUE THREAD

**Issue by studiozocaro** [Enough-Software/enough_mail#52]
flutter: C: a12 FETCH -23:7 (BODY.PEEK[HEADER] BODYSTRUCTURE FLAGS)
flutter: S: a12 BAD Could not parse command

Bug when change folder select   from -23

**Comment by studiozocaro** [comment]
bug when set  messageCount: 30 and in folder i have 7 emails.
 
code:
 var fetchResponse = await client.fetchRecentMessages(
            messageCount: 30,
            criteria:
                '(BODY.PEEK[HEADER] BODYSTRUCTURE FLAGS)');

**Comment by studiozocaro** [comment]
solution:
in imap_client.dart
add on raw 802
if (lowerMessageSequenceId < 1) lowerMessageSequenceId = 1;

**Comment by robert-virkus** [comment]
Many thanks for your contribution - this is fixed with v0.0.19, I also mentioned you on the release notes: https://pub.dev/packages/enough_mail/versions/0.0.19#-changelog-tab-
