### ISSUE TITLE
bug smtp

### ISSUE THREAD

**Issue by studiozocaro** [Enough-Software/enough_mail#53]
flutter: S: 220 win18.misterdomain.eu ESMTP MailEnable Service, Version: 10.27-- ready at 05/14/20 14:53:12
flutter: S:
flutter: C: EHLO enough.de
flutter: S: 250-win18.misterdomain.eu [5.90.170.34], this server offers 5 extensions
flutter: S: 250-AUTH LOGIN
flutter: S: 250-SIZE 52428800
flutter: S: 250-HELP
flutter: S: 250-AUTH=LOGIN
flutter: S: 250 STARTTLS
flutter: S:
flutter: C: AUTH PLAIN <base64 code scrambled>
flutter: S: 504 PLAIN authentication is not permitted by this server.
flutter: S:

**Comment by robert-virkus** [comment]
Hi, currently only plain login is supported. I see that STARTTLS is provided, you should first switch to TLS by calling `smtpClient.startTls()` in this case. You can also try to directly connect to SSL, e.g.
```dart
var smtpClient = SmptClient('enough.de', isLogEnabled: true);
smtpClient.connectToServer('win18.misterdomain.eu', 465, isSecure: true);
```

If that does not work for you, I guess we need to implement `AUTH LOGIN`, this is described in more details here: https://www.samlogic.net/articles/smtp-commands-reference-auth.htm

**Comment by robert-virkus** [comment]
AUTH LOGIN is now also supported.

**Comment by studiozocaro** [comment]
Perfect
