### ISSUE TITLE
how to use "Support CONDSTORE IMAP extension"?

### ISSUE THREAD

**Issue by studiozocaro** [Enough-Software/enough_mail#54]
how to use "Support CONDSTORE IMAP extension"?

**Comment by robert-virkus** [comment]
Hi, please check https://tools.ietf.org/html/rfc7162 for details about CONDSTORE. 

CONDSTORE makes the following changes to the IMAP4 protocol:

1. adds the UNCHANGEDSINCE STORE modifier.
2. adds the MODIFIED response code that is used with an OK response to the STORE command.  (It can also be used in a NO response.)
3. adds a new MODSEQ message data item for use with the FETCH command.
4. adds the CHANGEDSINCE FETCH modifier.
5. adds a new MODSEQ search criterion.
6. extends the syntax of untagged SEARCH and ESEARCH responses to include mod-sequence.
7. adds new OK untagged responses (HIGHESTMODSEQ and NOMODSEQ) for the SELECT and EXAMINE commands.
8. defines an additional CONDSTORE parameter to SELECT/EXAMINE commands.
9. adds the HIGHESTMODSEQ status data item to the STATUS command.
