### ISSUE TITLE
subject no encoding found for [iso-8859-15].

### ISSUE THREAD

**Issue by studiozocaro** [Enough-Software/enough_mail#55]
flutter: Error: no encoding found for [iso-8859-15].

**Comment by robert-virkus** [comment]
I have added basic support in v0.0.21, however Dart currently does not seem to support latin-2 to latin-16 character encoding standards, so this is falling back to UTF-8 for now.

**Comment by robert-virkus** [comment]
I have added proper support for `iso-8859-15` encoding so this should be fixed now from version v0.0.35 onward. If not please reopen.
