### ISSUE TITLE
how to count unseen without use client.selectMailbox?

### ISSUE THREAD

**Issue by studiozocaro** [Enough-Software/enough_mail#56]
how to count unseen without use select client.selectMailbox?

**Comment by robert-virkus** [comment]
You can use status call: `ImapClient.statusMailbox(..)`, compare https://pub.dev/documentation/enough_mail/latest/imap_imap_client/ImapClient/statusMailbox.html

**Comment by studiozocaro** [comment]
i have random unexpected STATUS:
flutter: unexpected STATUS: (UNSEEN=45
in STATUS "[Gmail]/Tutti i messaggi" (UNSEEN 45)

**Comment by studiozocaro** [comment]
flutter: Folder name: "Fattury log"
flutter: unexpected STATUS: (UNSEEN=0
in STATUS "Fattury log" (UNSEEN 0)
flutter: details: null
flutter: details: ResponseStatus.OK
flutter: Folder name: "INBOX"
flutter: unexpected STATUS: (UNSEEN=44
in STATUS "INBOX" (UNSEEN 44)
flutter: details: null
flutter: details: ResponseStatus.OK
flutter: 0
flutter: Folder name: "Mailspring"
flutter: unexpected STATUS: (UNSEEN=0
in STATUS "Mailspring" (UNSEEN 0)
flutter: details: null
flutter: details: ResponseStatus.OK
flutter: Folder name: Snoozed"
flutter: unexpected STATUS: (UNSEEN=0
in STATUS "Mailspring/Snoozed" (UNSEEN 0)
flutter: details: null
flutter: details: ResponseStatus.OK
flutter: Folder name: "Notes"
flutter: unexpected STATUS: (UNSEEN=0
in STATUS "Notes" (UNSEEN 0)
flutter: details: null
flutter: details: ResponseStatus.OK
flutter: Folder name: "OVH"
flutter: unexpected STATUS: (UNSEEN=1
in STATUS "OVH" (UNSEEN 1)
flutter: details: null
flutter: details: ResponseStatus.OK
flutter: Folder name: "[Gmail]"
flutter: Folder name: Bozze"
flutter: unexpected STATUS: (UNSEEN=0
in STATUS "[Gmail]/Bozze" (UNSEEN 0)
flutter: details: null
flutter: details: ResponseStatus.OK
flutter: Folder name: Cestino"
flutter: unexpected STATUS: (UNSEEN=0
in STATUS "[Gmail]/Cestino" (UNSEEN 0)
flutter: details: null
flutter: details: ResponseStatus.OK
flutter: *************** cestino trovato ********************
flutter: Folder name: Importanti"
flutter: unexpected STATUS: (UNSEEN=44
in STATUS "[Gmail]/Importanti" (UNSEEN 44)
flutter: details: null
flutter: details: ResponseStatus.OK
flutter: Folder name: Posta inviata"
flutter: unexpected STATUS: (UNSEEN=4
in STATUS "[Gmail]/Posta inviata" (UNSEEN 4)
flutter: details: null
flutter: details: ResponseStatus.OK
flutter: Folder name: Spam"
flutter: unexpected STATUS: (UNSEEN=0
in STATUS "[Gmail]/Spam" (UNSEEN 0)
flutter: details: null
flutter: details: ResponseStatus.OK
flutter: Folder name: Speciali"
flutter: unexpected STATUS: (UNSEEN=0
in STATUS "[Gmail]/Speciali" (UNSEEN 0)
flutter: details: null
flutter: details: ResponseStatus.OK
flutter: Folder name: Tutti i messaggi"
flutter: unexpected STATUS: (UNSEEN=45
in STATUS "[Gmail]/Tutti i messaggi" (UNSEEN 45)
flutter: details: null
flutter: details: ResponseStatus.OK

**Comment by studiozocaro** [comment]
flutter: unexpected STATUS: (UNSEEN=0
in STATUS "Fattury log" (UNSEEN 0)
flutter: unexpected STATUS: (UNSEEN=44
in STATUS "INBOX" (UNSEEN 44)
flutter: unexpected STATUS: (UNSEEN=0
in STATUS "Mailspring" (UNSEEN 0)
flutter: unexpected STATUS: (UNSEEN=0
in STATUS "Mailspring/Snoozed" (UNSEEN 0)
flutter: unexpected STATUS: (UNSEEN=0
in STATUS "Notes" (UNSEEN 0)
flutter: unexpected STATUS: (UNSEEN=1
in STATUS "OVH" (UNSEEN 1)
flutter: unexpected STATUS: (UNSEEN=0
in STATUS "[Gmail]/Bozze" (UNSEEN 0)
flutter: unexpected STATUS: (UNSEEN=0
in STATUS "[Gmail]/Cestino" (UNSEEN 0)
flutter: unexpected STATUS: (UNSEEN=44
in STATUS "[Gmail]/Importanti" (UNSEEN 44)
flutter: unexpected STATUS: (UNSEEN=4
in STATUS "[Gmail]/Posta inviata" (UNSEEN 4)
flutter: unexpected STATUS: (UNSEEN=0
in STATUS "[Gmail]/Spam" (UNSEEN 0)
flutter: unexpected STATUS: (UNSEEN=0
in STATUS "[Gmail]/Speciali" (UNSEEN 0)
flutter: unexpected STATUS: (UNSEEN=45
in STATUS "[Gmail]/Tutti i messaggi" (UNSEEN 45)

**Comment by studiozocaro** [comment]
with log imap:
flutter: S: * STATUS "Fattury log" (UNSEEN 0)
flutter: unexpected STATUS: (UNSEEN=0
in STATUS "Fattury log" (UNSEEN 0)
flutter: S: a8 OK Success
flutter: S: * STATUS "INBOX" (UNSEEN 44)
flutter: unexpected STATUS: (UNSEEN=44
in STATUS "INBOX" (UNSEEN 44)
flutter: S: a9 OK Success
flutter: S: * STATUS "Mailspring" (UNSEEN 0)
flutter: unexpected STATUS: (UNSEEN=0
in STATUS "Mailspring" (UNSEEN 0)
flutter: S: a10 OK Success
flutter: S: * STATUS "Mailspring/Snoozed" (UNSEEN 0)
flutter: unexpected STATUS: (UNSEEN=0
in STATUS "Mailspring/Snoozed" (UNSEEN 0)
flutter: S: a11 OK Success
flutter: S: * STATUS "Notes" (UNSEEN 0)
flutter: unexpected STATUS: (UNSEEN=0
in STATUS "Notes" (UNSEEN 0)
flutter: S: a12 OK Success
flutter: S: * STATUS "OVH" (UNSEEN 1)
flutter: unexpected STATUS: (UNSEEN=1
in STATUS "OVH" (UNSEEN 1)
flutter: S: a13 OK Success
flutter: S: * STATUS "[Gmail]/Bozze" (UNSEEN 0)
flutter: unexpected STATUS: (UNSEEN=0
in STATUS "[Gmail]/Bozze" (UNSEEN 0)
flutter: S: a14 OK Success
flutter: S: * STATUS "[Gmail]/Cestino" (UNSEEN 0)
flutter: unexpected STATUS: (UNSEEN=0
in STATUS "[Gmail]/Cestino" (UNSEEN 0)
flutter: S: a15 OK Success
flutter: S: * STATUS "[Gmail]/Importanti" (UNSEEN 44)
flutter: unexpected STATUS: (UNSEEN=44
in STATUS "[Gmail]/Importanti" (UNSEEN 44)
flutter: S: a16 OK Success
flutter: S: * STATUS "[Gmail]/Posta inviata" (UNSEEN 4)
flutter: unexpected STATUS: (UNSEEN=4
in STATUS "[Gmail]/Posta inviata" (UNSEEN 4)
flutter: S: a17 OK Success
flutter: S: * STATUS "[Gmail]/Spam" (UNSEEN 0)
flutter: unexpected STATUS: (UNSEEN=0
in STATUS "[Gmail]/Spam" (UNSEEN 0)
flutter: S: a18 OK Success
flutter: S: * STATUS "[Gmail]/Speciali" (UNSEEN 0)
flutter: unexpected STATUS: (UNSEEN=0
in STATUS "[Gmail]/Speciali" (UNSEEN 0)
flutter: S: a19 OK Success
flutter: S: * STATUS "[Gmail]/Tutti i messaggi" (UNSEEN 45)
flutter: unexpected STATUS: (UNSEEN=45
in STATUS "[Gmail]/Tutti i messaggi" (UNSEEN 45)
flutter: S: a20 OK Success

**Comment by studiozocaro** [comment]
i have edit staus_parser.dart:
  var entry = listEntries[i].replaceAll('(', '');

**Comment by studiozocaro** [comment]
after version 21 persist error

i have edit staus_parser.dart:
var entry = listEntries[i].replaceAll('(', '');

**Comment by robert-virkus** [comment]
Hi many thanks for your work! Do you know how to create a pull request? You can even edit the file here on GitHub to fork and then create a  corresponding pull request - that would be awesome!

Thanks in advance,
yours
  Robert

**Comment by robert-virkus** [comment]
Fixed with v0.0.23
