### ISSUE TITLE
how do i decode the html like ".decodeTextHtmlPart()" when i request a part of the body?

### ISSUE THREAD

**Issue by studiozocaro** [Enough-Software/enough_mail#58]
how do i decode the html like ".decodeTextHtmlPart()" when i request a part of the body?
fetch 'uid BODY[1.2]'
I have the answer  in .bodyRaw:

        if (partemime.contentType.mediaType.toString() == 'text/html') {     
          fetchHeaderResponse = await globals.client
              .uidFetchMessage(mailContent.uid, 'BODY[$parte]');

fetchHeaderResponse.result.first.body.parts.first.bodyRaw

**Comment by robert-virkus** [comment]
Good question, the problem is that the `content-transfer-encoding` is not specified in this body structure. If you just fetch the whole message with `BODY[]` then you can of course call `mimePart.decodeContentText()` or `mimeMessage.decodeTextHtml()`.

**Comment by robert-virkus** [comment]
The high level `MailClient` API now does this for you when fetching message contents with `final messageWithContents = await MailClient.fetchMessageContents(mimeMessage, maxSize: 64*1024);`
Also the decode methods use the information from a previously downloaded body structure.
