### ISSUE TITLE
How to download only attachment part?

### ISSUE THREAD

**Issue by studiozocaro** [Enough-Software/enough_mail#60]
I read from server email strutture, 
How to download only specify attachment part (example access_log.txt)?

--Apple-Mail=_484F9CAD-D85B-4127-99F8-922252BBF45B
Content-Disposition: attachment;
	filename=access_log.txt
Content-Type: text/plain;
	x-unix-mode=0644;
	name="access_log.txt"
Content-Transfer-Encoding: quoted-printable

**Comment by robert-virkus** [comment]
Hey, it's .... complicated. Maybe this can help you: https://stackoverflow.com/questions/37787767/fetch-imap-body-message-by-telnet

So the idea is first to `FETCH` the `BODYSTRUCTURE` and based on that download the specific message parts.

**Comment by robert-virkus** [comment]
By the way, you can now query the part's fetch ID by calling `bodyPart.fetchId`.

**Comment by studiozocaro** [comment]
thanks a lot

**Comment by robert-virkus** [comment]
In v0.0.31 you can now also download individual message parts using  the high level API using `MailClient.fetchMessagePart(MimeMessage message, String fetchId)`.

**Comment by mjmon** [comment]
> In v0.0.31 you can now also download individual message parts using the high level API using `MailClient.fetchMessagePart(MimeMessage message, String fetchId)`.

I cant see `fetchMessagePart` among client methods. I'm using `enough_mail: ^0.0.32`

![Screen Shot 2020-08-14 at 1 51 37 PM](https://user-images.githubusercontent.com/41887404/90218043-66599000-de35-11ea-9c80-30207a5ac761.png)

**Comment by robert-virkus** [comment]
This screenshot is showing the `ImapClient` methods, which is the low level API. Above I am referring to the high level API using `MailClient` instead. You can also fetch message parts using `imapClient.fetchMessage()` but not as comfortably.
