### ISSUE TITLE
how to send copy message send via imap?

### ISSUE THREAD

**Issue by studiozocaro** [Enough-Software/enough_mail#61]
how to send the copy of the message sent via smtp to the imap server?

**Comment by robert-virkus** [comment]
Just use`ImapClient.appendMessage()` for this, e.g.
```dart
await client.appendMessage(message, flags: [r'\Seen'], targetMailboxPath: 'Sent');
```
Note that the `targetMailboxPath` is server specific. Compare https://pub.dev/documentation/enough_mail/latest/imap_imap_client/ImapClient/appendMessage.html for details.

**Comment by studiozocaro** [comment]
thanks

**Comment by studiozocaro** [comment]
PLAIN authentication is not permitted by this server:


flutter: C: EHLO Fmail
flutter: S: 250-win18.misterdomain.eu [5.90.170.34], this server offers 4 extensions
flutter: S: 250-AUTH LOGIN
flutter: S: 250-SIZE 52428800
flutter: S: 250-HELP
flutter: S: 250 AUTH=LOGIN
flutter: S:
flutter: C: AUTH PLAIN <base64 code scrambled>
flutter: S: 504 PLAIN authentication is not permitted by this server.
flutter: S:

**Comment by robert-virkus** [comment]
Compare #53
