### ISSUE TITLE
smtp gmail

### ISSUE THREAD

**Issue by studiozocaro** [Enough-Software/enough_mail#62]
Exception has occurred.
HandshakeException (HandshakeException: Handshake error in client (OS Error: 
	WRONG_VERSION_NUMBER(tls_record.cc:242)))

**Comment by studiozocaro** [comment]
gmail work on port 465.
tls not work on 587

**Comment by robert-virkus** [comment]
465 is the standard SMTPS port, so you need to set the `isSecure` parameter to `true`:
```dart
var client = SmtpClient('enough.de', isLogEnabled: true);
await client.connectToServer('smtp.gmail.com', 465, isSecure: true);
```

587 is the STARTTLS port, so you have to set `isSecure` to `false`:
```dart
var client = SmtpClient('enough.de', isLogEnabled: true);
await client.connectToServer('smtp.gmail.com', 587, isSecure: false);
```
So this is not a bug.

**Comment by studiozocaro** [comment]
Thanks

⁣Ing. Flavio Zocaro

Ottieni BlueMail per Android ​

Il giorno 1 giu 2020, 11:13, alle ore 11:13, Robert Virkus <notifications@github.com> ha scritto:
