### ISSUE TITLE
error parse bodystructure fetch_parser.dart

### ISSUE THREAD

**Issue by studiozocaro** [Enough-Software/enough_mail#64]
2175 FETCH (UID 3641 FLAGS (\Seen) BODYSTRUCTURE (((("TEXT" "PLAIN" ("CHARSET" "UTF-8") NIL NIL "QUOTED-PRINTABLE" 274 6 NIL NIL NIL)("TEXT" "HTML" ("CHARSET" "UTF-8") NIL NIL "QUOTED-PRINTABLE" 1455 30 NIL NIL NIL) "ALTERNATIVE" ("BOUNDARY" "0000000000002f322a05a71aaf69") NIL NIL)("IMAGE" "PNG" ("NAME" "icon.png") "<icon.png>" NIL "BASE64" 1986 NIL ("ATTACHMENT" ("FILENAME" "icon.png")) NIL) "RELATED" ("BOUNDARY" "0000000000002f322205a71aaf68") NIL NIL)("MESSAGE" "DELIVERY-STATUS" NIL NIL NIL "7BIT" 488 NIL NIL NIL)("MESSAGE" "RFC822" NIL NIL NIL "7BIT" 2539 ("Tue, 2 Jun 2020 16:25:29 +0200" "tested" (("Flavio" NIL "studio" "gmail.com")) (("Flavio" NIL "studio" "gmail.com")) (("Flavio" NIL "studio" "gmail.com")) (("studio@gmail.com" NIL "studio" "gmail.com")("Anna Haro" NIL "anna-haro" "mac.com")) NIL NIL NIL "<GDQBjfh3TAG63B@gmail.com>") (("TEXT" "PLAIN" ("CHARSET" "utf8") NIL NIL "7BIT" 0 0 NIL NIL NIL)("TEXT" "HTML" ("CHARSET" "utf8") NIL NIL "8BIT" 1 1 NIL NIL NIL) "ALTERNATIVE" ("BOUNDARY" "C6WuYgfyNiVn6u" "CHARSET" "utf8") NIL NIL) 51 NIL NIL NIL) "REPORT" ("BOUNDARY" "0000000000002f1f3705a71aaf47" "REPORT-TYPE" "delivery-status") NIL NIL)
 BODY[HEADER.FIELDS (DATE FROM SUBJECT TO CC MESSAGE-ID REFERENCES CONTENT-TYPE CONTENT-DESCRIPTION IN-REPLY-TO REPLY-TO LINES LIST-POST X-LABEL)]

**Comment by studiozocaro** [comment]
contentDisposition is null. (parts[0].value).

**my correction on raw 247:**
  if (parts[0].value != null) {
            var contentDisposition =
                ContentDispositionHeader(parts[0].value?.toLowerCase());
            var parameters = parts[1].children;
            if (parameters != null && parameters.length > 1) {
              for (var i = 0; i < parameters.length; i += 2) {
                contentDisposition.setParameter(
                    parameters[i].value, parameters[i + 1].value);
              }
            }
            part.contentDisposition = contentDisposition;
          } else {
            return;
          }

**Comment by robert-virkus** [comment]
check out v0.0.24 which fixes this problem by correctly parsing `message/rfc822` parts in the `BODYSTRUCTURE` response.
