### ISSUE TITLE
error  in quoted_printable_mail_codec.dart

### ISSUE THREAD

**Issue by studiozocaro** [Enough-Software/enough_mail#65]
enough_mail-0.0.21/lib/codecs/quoted_printable_mail_codec.dart

error invalid number(150

**row 118: correct**
 try {
            var decoded = codec.decode(charCodes);
            buffer.write(decoded);
          } catch (e) {}

**Comment by robert-virkus** [comment]
Hm, I am unsure if we should just silently fail to decode in this case. Do you have input that fails? Maybe it is possible to fix the root cause....

**Comment by robert-virkus** [comment]
Closing this for now
