### ISSUE TITLE
Listening to new emails seems to be not working in high-level api

### ISSUE THREAD

**Issue by dantsushko** [Enough-Software/enough_mail#68]
Hi, Robert, I'm trying to start using your library but I've got some troubles. I'm running your example (mailExampe) and it seems ok -  I can see messages from my inbox. But this part of code: 

``` mailClient.eventBus.on<MailLoadEvent>().listen((event) {```
      ```         print('New message at ${DateTime.now()}:');```
 ```});```
 ```await mailClient.startPolling();```
is not reacting when I get new message
What am I doing wrong?

**Comment by robert-virkus** [comment]
Hi Dantsushko,

it may very well be a bug in the code. Please try to the following: enable logging in the mailClient by setting `isLogEnabled` to true:
```dart
var mailClient = MailClient(account, isLogEnabled: true);
```

Please now start your code and send yourself a message. You should see the corresponding IMAP/POP debug output. Can you post this debug output here or send me output?   I am only interested in the output after you called `startPolling()`.

Thanks,
  Robert

**Comment by dantsushko** [comment]
Thanks for fast reply) Here is the full output, cause I see no "IMAP/POP debug output"

discovering settings for  my@email.ru...
connecting to mail.ru.
Connecting to imap.mail.ru:993  using a secure socket...
Socket connected.
C: a0 LOGIN my@email.ru (password scrambled)
S: * OK IMAP4 ready

untagged not handled: [* OK IMAP4 ready
] by task a0 LOGIN my@email.ru (password scrambled)
S: * CAPABILITY IMAP4rev1 ID XLIST UIDPLUS UNSELECT MOVE LIST-STATUS

S: a0 OK Authentication successful

connected
C: a1 NOOP
S: a1 OK NOOP completed

Sending emails to my@email.ru doesn't produce log entries.
Perhaps there are some troubles with my IMAP server?

**Comment by robert-virkus** [comment]
Thanks for the log output! Your IMAP server does not support `IDLE`, so what should happen is that the `MailClient` regularly polls for new messages using `NOOP`. The default polling duration is 2 minutes, you can define the duration optionally in the `startPolling()` call, e.g.
```dart
await mailClient.startPolling(Duration(seconds: 20));
```
You should see the `NOOP` command executed regularly and at the next `NOOP` call after receiving a message a `* FETCH...` or `* 123 EXISTS` or similar so called untagged response from the server should show up.

I haven't found a way to register a new account at email.ru, can you share a test account privately with me?

**Comment by dantsushko** [comment]
Thanks a lot! I've tried another mail (yandex.ru) and listener worked fine. Seems that there is a problem with mail.ru, I've created an account so you can use it for testing
email: enough_mail@mail.ru
password: yTiRS3P1e$du

**Comment by robert-virkus** [comment]
Thanks for the account! I will look at this is in more detail over the weekend.

**Comment by robert-virkus** [comment]
Thanks again for the test account. Polling worked for me - new messages are printed as they come in - but my messages did end up in the Spam folder `'&BCEEPwQwBDw-'` and not in the Inbox. 

Looking at the folder name I also realize that enough_mail currently does not decode mailbox names correctly, I created issue #69 for this.

**Comment by dantsushko** [comment]
In my case I decided not to use polling, but run checking email on schedule, anyway many thanks for your job)

BTW there is a small remark about examples, I dont know whether to create an issue about it.
I think in your examples you should add `client.closeConnection()` because if you run your example many times, you will have a lot of opened tcp connections listening to IMAP socket. I didn't find closeConnection method in MailClient, only in ImapClient

**Comment by robert-virkus** [comment]
Thanks for the suggestion, I will add a highlevel `disconnect()` method with the next release. Keeping this ticket open until then,

**Comment by robert-virkus** [comment]
Added a `mailClient.disconnect()` method in release v0.0.29
