### ISSUE TITLE
Problems with encoding

### ISSUE THREAD

**Issue by dantsushko** [Enough-Software/enough_mail#70]
Hello again! I've encountered another issue, perhaps it is connected with local Russian mail providers I don't know exactly.
The message has such headers: 

Content-Type: text/plain; charset=utf-8; format=flowed
Content-Transfer-Encoding: 8bit

The message itself consists of such symbols and there is no way to decode them, because they are in bodyRaw
Ð¡ ÑÐ²Ð°Ð¶ÐµÐ½Ð¸ÐµÐ¼, ÐÐ°Ð´Ð¸Ð¼ Ð¦ÑÑÐºÐ¾
Ð ÑÐºÐ¾Ð²Ð¾Ð´Ð¸ÑÐµÐ»Ñ Ð½Ð°Ð¿ÑÐ°Ð²Ð»ÐµÐ½Ð¸Ñ Ð¼Ð¾Ð´ÐµÐ»Ð¸ÑÐ¾Ð²Ð°Ð½Ð¸Ñ

I can send such message to your test account if it helps

**Comment by dantsushko** [comment]
The same message contains correct characters on the other server, so this is mail.ru bug, I close this issue

**Comment by robert-virkus** [comment]
You can call `mimeMessage.decodeTextPlainPart()`, `decodeTextHtmlPart()`, etc if you want to access the text message contents.
In most cases it's probably best to recursively go through all mime parts and depending on the mime type of that part select the appropriate action.
