### ISSUE TITLE
fetch single message

### ISSUE THREAD

**Issue by GiacomoK** [Enough-Software/enough_mail#74]
Hi,  
I did not understand how can I fetch a single message once I downloaded the headers of all messages with fetchMessages.

**Comment by robert-virkus** [comment]
I assume that you are using the low level API with `ImapClient` . Note that you need some IMAP know how when using the low level API. 

You probably have fetched the message header with 
`ImapClient.fetchMessage(1, '(HEADER[])');` or similar, 1 being the message's sequence ID in this case. Use `BODY[]` or `BODY.PEEK[]` to fetch the complete message, for example:
```dart
var response = await imapClient.fetchMessage(1, '(UID BODY.PEEK[])');
if (response.isOkStatus) {
   var mimeMessage = response.result.first;
}
```

It might be simpler to use the high level API with using [MailClient](https://pub.dev/documentation/enough_mail/latest/mail_mail_client/MailClient-class.html). Also compare the [example](https://pub.dev/documentation/enough_mail/latest/). The high level API tries to abstract away common use cases and allows you to support both IMAP and POP3 with a common API.

Hope this helps!

**Comment by GiacomoK** [comment]
Thank you for your answer.
About high level API, I was not able to fetch a single message (there is no `fetchMessage` function in `MailClient` class), that's why I am using low level API.

Do you know where I can find IMAP docs for retrieve mail informations? (`BODY[]`, `BODY.PEEK[]`, ecc.)

**Comment by robert-virkus** [comment]
Sorry for the late reply. You can find all information in the [RFC 3501](https://tools.ietf.org/html/rfc3501). 

You can also call `MailClient.fetchMessageContents(MimeMessage message)` to download the complete message.

**Comment by robert-virkus** [comment]
Closing this for now, please reopen if you need more info about this topic.
