### ISSUE TITLE
If you create apk and install on a device, the connect to Imap server seems not working

### ISSUE THREAD

**Issue by GiacomoK** [Enough-Software/enough_mail#75]
Hi,  
in debug I can connect to Imap server and login.

If I create the apk and install it on a device, this code:

    _imapClient = ImapClient(isLogEnabled: true);
    await _imapClient.connectToServer(imapServerHost, imapServerPort, isSecure: isImapServerSecure);
    return await _imapClient.login(email, password);

seems not working. I do not get an answer from the server.

**Comment by robert-virkus** [comment]
Hi, do you see any output when running the app in release mode e.g. with `flutter run --release`?

If you see a Socket connection error such as `SocketException: Failed host lookup`, then please check your Android manifest in _android/app/src/main/AndroidManifest.xml_. Do you have specified the `INTERNET` permission there?
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.my_app">
    <uses-permission android:name="android.permission.INTERNET"/>
[...]
```

Hope this helps, if this resolves the problem please close this bug.
Best,
  Robert

**Comment by GiacomoK** [comment]
Yes it was the INTERNET permission missing.

Sorry for the stupid question. Thank you!
