### ISSUE TITLE
bodyPart.fetchId not working?

### ISSUE THREAD

**Issue by giacomok** [Enough-Software/enough_mail#76]
Hi,  
I am trying to view attachments of email.

To get attachments I use this recursive function:

    _attachments = [];

    void navigateTreeBody(tree) {
        for (final part in tree) {
            if (part.parts != null) {
                navigateTreeBody(part.parts);
            }
            if (part.contentDisposition != null && part.contentDisposition.rawValue == 'attachment') {
                _attachments.add(new Attachment(part.contentDisposition.filename, part.fetchId));
            }
        }
    }

For every attachment I save the name and the path to fetch If I want. The `Attachment` class has `name` and `bodyPart` members.  
After that I try this code to download the file:

    var response = await _imapClient.fetchMessage(messageId, '(BODY[' + attachment.bodyPart + '])'); // for ex. (BODY[1.3.1.2])

but I always get null values for all fields except messageId, even if I get the path from the part itself.  
Where am I wrong?

**Comment by robert-virkus** [comment]
There was a bug when encountering `BODY[1.2]` etc replies. This should be fixed in the release v0.0.31. You can now call `mimeMessage.getPart(String fetchId)` to see if a specific message part is already present in the message.

Please close this issue if this solves your use case.

**Comment by Tienisto** [comment]
It is working now

**Comment by robert-virkus** [comment]
Thanks for confirming!
