### ISSUE TITLE
Quoted-Printable vs. Q-Encoding

### ISSUE THREAD

**Issue by hpoul** [Enough-Software/enough_mail#77]
Hi,
I think there is some confusion in the `QuotedPrintableMailCodec` - It references [RFC 2045 Quoted-Printable](https://tools.ietf.org/html/rfc2045#page-19), but at least partially implements [RFC 2047 "Q" Encoding](https://tools.ietf.org/html/rfc2047#section-4.2).

At least the problem i've stumbled upon was:

https://github.com/Enough-Software/enough_mail/blob/1f95f82c5ee0867c7f52d596bea09e2a5ab1407f/lib/codecs/quoted_printable_mail_codec.dart#L123-L125

Underscores should not be decoded to a `SPACE` according to 2045, as far as I understand it.

Any thoughts? Is this supposed to decode Quoted-Printable or Q-Encoding?

**Comment by hpoul** [comment]
Unfortunately I'm not really 100% fluent in RFCs :-) but how about simply introducing a 'header' flag which would switch between Quoted-Printabe (header=false) vs. "Q" Encoding (header=true) - this is how python seems to implement it:

https://github.com/python/cpython/blob/46e448abbf35c051e5306a4695670d7ec7abc4e9/Lib/quopri.py#L141-L144

**Comment by robert-virkus** [comment]
Thanks Herbert, let me check out the RFCs and then work on the fixes. Possibly it's cleaner to provide a separate codec implementation for both sub encoding types.

**Comment by robert-virkus** [comment]
This should be fixed in release v0.0.32 now

**Comment by hpoul** [comment]
@robert-virkus looks good, thanks!
