### ISSUE TITLE
Attachment info not showing in builder.buildMimeMessage()?

### ISSUE THREAD

**Issue by winnie-chaintope** [Enough-Software/enough_mail#88]
I was wondering whether mimeMessage suppose to return the attachment info as well?
Reason being i am not using the client to send the email; i just need mimeMessage with attachments info to do some encryptions.

    ```final MessageBuilder builder = MessageBuilder.prepareMultipartMixedMessage();
    final File attachment = File('/sample.zip');
    await builder.addFile(attachment, MediaType.fromSubtype(MediaSubtype.applicationZip));
    builder.from = [MailAddress('Sender', 'test@test.com')];
    builder.to = [MailAddress('Receiver', 'test@test.com')];
    builder.subject = 'Test Email Attachments';

    final MimeMessage mimeMessage = builder.buildMimeMessage();


    print('hasAttachments: ${mimeMessage.hasAttachments()}');
    print('mimeMessage: $mimeMessage');```


```
===LOG===
flutter: hasAttachments: true

flutter: mimeMessage: id: [null]
From: "Sender" <test@test.com>
To: "Receiver" <test@test.com>
Date: Wed, 30 Sep 2020 16:46:51 +0800
Message-Id: <9OswZznqJjPcEK@test.com>
Subject: Test Email Attachments
MIME-Version: 1.0
Content-Type: multipart/mixed; charset="utf8"; boundary="dn5Y9cXB4XmKJd"
Content-Transfer-Encoding: 8bit
```

**Comment by robert-virkus** [comment]
Hi Winnie,

not sure if I get your problem right, did you try calling `mimeMessage.renderMessage()`?

**Comment by winnie-chaintope** [comment]
yes this is what i am looking for 
thanks for the quick response 
i will close this issue

**Comment by robert-virkus** [comment]
With the next version I willl also change the code, so that `toString()` actually calls `renderMessage()`.
