### ISSUE TITLE
 HighLevel API Usage, The getter 'preferredIncomingServer' was called on null

### ISSUE THREAD

**Issue by mjmon** [Enough-Software/enough_mail#90]
I tried to implement the high-level example on the document below.

`import 'package:enough_mail/enough_mail.dart';

String userName = 'myuser';
String password = 'mypassword';

void main() async {
  await mailExample();
}

Future<void> mailExample() async {
  var email = userName + '@hallohands.dk';
  var config = await Discover.discover(email);
  var account = MailAccount.fromDiscoveredSetings(
      'my account', email, password, config,
      outgoingClientDomain: 'hallohands.dk');
  var mailClient = MailClient(account, isLogEnabled: true);
  await mailClient.connect();
  var mailboxesResponse =
      await mailClient.listMailboxesAsTree(createIntermediate: false);
  if (mailboxesResponse.isOkStatus) {
    print(mailboxesResponse.result);
    await mailClient.selectInbox();
    var fetchResponse = await mailClient.fetchMessages(count: 20);
    if (fetchResponse.isOkStatus) {
      for (var msg in fetchResponse.result) {
        print('msg: $msg');
      }
    }
  }
  mailClient.eventBus.on<MailLoadEvent>().listen((event) {
    print('New message at ${DateTime.now()}:');
    print('message: ${event.message}');
  });
  mailClient.startPolling();
}`

But got this error, Where should I put `preferredIncomingServer` because I can't see it on the named parameters

```
Restarted application in 438ms.
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The getter 'preferredIncomingServer' was called on null.
Receiver: null
Tried calling: preferredIncomingServer
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      MailAccount.fromDiscoveredSetings (package:enough_mail/mail/mail_account.dart:46:25)
#2      mailExample (package:email_listener/main.dart:13:29)
<asynchronous suspension>
#3      main (package:email_listener/main.dart:7:9)
#4      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:241:25)
#5      _rootRun (dart:async/zone.dart:1184:13)
#6      _CustomZone.run (dart:async/zone.dart:1077:19)
#7      _runZoned (dart:async/zone.dart:1619:10)
#8      runZonedGuarded (dart:async/zone.dart:1608:12)
#9      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:233:5)
#10     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_pat<…>

```

**Comment by robert-virkus** [comment]
My assumption is that `config = await Discover.discover(email);` returns null, indicating that that settings for the specified email address could not be resolved automatically. In that case you need to use other means, eg asking the user for the appropriate settings, If you believe the email address should have beeen resolved automatically, please let me know the address or the domain.

**Comment by mjmon** [comment]
Hello @robert-virkus  thank you for your quick response

I'm using the email server
`final String _server = 'mail.hallohands.dk';`
email is `'junille@hallohands.dk'`.

I was able to fetch the emails for inbox but listening doesnt seems to work and it's with the above error logs

**Comment by mjmon** [comment]
was able to fix using 
```
    var config = new ClientConfig();
    var emailProv = new ConfigEmailProvider(displayName: 'Test Name');
    emailProv.addDomain('hallohands.dk');
    emailProv.addIncomingServer(new ServerConfig(
      type: ServerType.imap,
      hostname: 'mail.hallohands.dk',
      socketType: SocketType.ssl,
      authentication: Authentication.plain,
      usernameType: UsernameType.emailAddress,
      port: 993,
    ));
```

**Comment by salahdine2020** [comment]
Hi evry one I get the same error pleas any one helpe me i need this plugin for a client : 

import 'package:flutter/material.dart';
import 'package:imap_client/imap_client.dart';
import 'package:enough_mail/enough_mail.dart';
import 'dart:io';

String userName = 'mailerexample2';
String password = '*********';
String name = 'mailer example‬‏';
void main() async {
  await mailExample();
  //await popExample();
  runApp(Home());
}
class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: HomeLance(),
    );
  }
}
class HomeLance extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Error'),
      ),
      body: Center(
        child: Text('Oh My Good'),
      ),
    );
  }
}

Future<void> mailExample() async {
  var email = userName + '@gmail.com';
  var config = await Discover.discover(email);
  var account =
  MailAccount.fromDiscoveredSetings(name, email, password, config);
  var mailClient = MailClient(account, isLogEnabled: true);
  await mailClient.connect();
  var mailboxesResponse =
  await mailClient.listMailboxesAsTree(createIntermediate: false);
  if (mailboxesResponse.isOkStatus) {
    print(mailboxesResponse.result);
    await mailClient.selectInbox();
    var fetchResponse = await mailClient.fetchMessages(count: 20);
    if (fetchResponse.isOkStatus) {
      for (var msg in fetchResponse.result) {
        print(msg);
      }
    }
  }
  mailClient.eventBus.on<MailLoadEvent>().listen((event) {
    print('New message at ${DateTime.now()}:');
    print(event.message);
  });
  mailClient.startPolling();
}

Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
Parameter format not correct -
√ Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...
Waiting for Android SDK built for x86 to report its views...
Syncing files to device Android SDK built for x86...
E/flutter ( 7950): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The getter 'preferredIncomingServer' was called on null.
E/flutter ( 7950): Receiver: null
E/flutter ( 7950): Tried calling: preferredIncomingServer
E/flutter ( 7950): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
E/flutter ( 7950): #1      MailAccount.fromDiscoveredSetings (package:enough_mail/mail/mail_account.dart:46:25)
E/flutter ( 7950): #2      mailExample (package:simple_mail_reader/main.dart:40:15)
E/flutter ( 7950): <asynchronous suspension>
E/flutter ( 7950): #3      main (package:simple_mail_reader/main.dart:10:9)
E/flutter ( 7950): #4      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:231:25)
E/flutter ( 7950): #5      _rootRun (dart:async/zone.dart:1190:13)
E/flutter ( 7950): #6      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter ( 7950): #7      _runZoned (dart:async/zone.dart:1630:10)
E/flutter ( 7950): #8      runZonedGuarded (dart:async/zone.dart:1618:12)
E/flutter ( 7950): #9      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:223:5)
E/flutter ( 7950): #10     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
E/flutter ( 7950): #11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter ( 7950):

**Comment by salahdine2020** [comment]
robert-virkus i send a message into ur facebook account if u can help me pleas

**Comment by mjmon** [comment]
I was able to fix it by using config below.
I hope it helps

`  Future emailListenConfig() async {
    var name ='Your Name';
    var email = 'youremail@somedomain.com';
    var password = 'your password';
    var config = new ClientConfig();
    var emailProv = new ConfigEmailProvider(displayName: name);
    emailProv.addDomain('somedomain.com');
    emailProv.addIncomingServer(new ServerConfig(
      type: ServerType.imap,
      hostname:'mail.somedomain.com',
      socketType: SocketType.ssl,
      authentication: Authentication.plain,
      usernameType: UsernameType.emailAddress,
      port: _imapPort,
    ));
    emailProv.addOutgoingServer(new ServerConfig(
      type: ServerType.smtp,
      hostname: _server,
      socketType: SocketType.ssl,
      authentication: Authentication.plain,
      usernameType: UsernameType.emailAddress,
      port: _smtpPort,
    ));

    config.addEmailProvider(emailProv);

    var account = MailAccount.fromDiscoveredSetings(
        name, email, password, config,
        userName: email, outgoingClientDomain: _clientDomain);
    _mailClient = MailClient(account, isLogEnabled: false);

    await _mailClient.connect();

    var mailboxesResponse =
        await _mailClient.listMailboxesAsTree(createIntermediate: false);
    if (mailboxesResponse.isOkStatus) {
      print(mailboxesResponse.result);
      var response = await _mailClient.selectInbox();
      print('total messages: ' + '${response?.result?.messagesExists}');
      var fetchResponse = await _mailClient.fetchMessages();
      var unseen =
          fetchResponse.result?.where((element) => !element.isSeen)?.length ??
              0;
      this.unseenCount = unseen;
      print('undread messages: ' + '$unseen');
      /*if (fetchResponse.isOkStatus) {
        for (var msg in fetchResponse.result) {
          print('msg: ${msg.isFlagged}');
        }
      }*/
      print('Ok status');
    }

    // mailClient.eventBus.on<MailLoadEvent>().listen((event) async {
    //   try {
    //     await notification('there\'s a new email', 'email received', 'message');
    //   } on Exception catch (_) {
    //     print(_);
    //   }

    //   print('New message at ${DateTime.now()}:');
    //   print('message: ${event.message}');
    // });

    _mailClient.startPolling(Duration(minutes: 5));
  }`

**Comment by salahdine2020** [comment]
thanx a lot mjmon i use the imapexample function and is work it fine
i wanna ask you if u know any methode to delet mails with enough_mail package and imap protocol 
or any other methode 
thank u for helpe

**Comment by mjmon** [comment]
@salahdine2020 Maybe using the Highlevel API to move [MimeMessage] to [Trash] mailbox would work.  First, you need to fetch the list of mailboxes because mailbox paths would vary between email servers. Opening up a separate issue would help as well.
