### ISSUE TITLE
How to implement Favorites

### ISSUE THREAD

**Issue by mjmon** [Enough-Software/enough_mail#91]
Hello and good day

How could I achieve adding a selected email to Favorites?
Should I assign a custom flag to an email and mark it as a favorite? or create a Mailbox named Favorites and make a copy of the email there?

I'm not sure how to achieve this. Looking forward to your response.

Thank you

**Comment by robert-virkus** [comment]
Assuming you have an IMAP server, you can mark a message with the `\Flagged` flag. 

In the high level API you can call `await mailClient.flagMessage(mimeMessage, isFlagged: true);`

In the low level API you can call call `await imapClient.store(messageSequence, [MessageFlags.flagged], action: StoreAction.add, silent: true);` or simply `await imapClient.markFlagged(messageSequence);`.

I plan to add support for easily retrieving messages using the high level API, soon. For now you can use the low level `imapClient.searchMessages('FLAGGED')` call to find the IDs of all flagged messages.
Compare https://tools.ietf.org/html/rfc3501#section-6.4.4 for details.

**Comment by mjmon** [comment]
Marking it with using `imapClient.markFlagged(messageSequence)` doesnt seem to work, the `mimeMessage.isFlagged` boolean value stays the same.

This is how I do it. Is their something missing on this my code?

```
await imapClient.selectInbox();
await imapClient.markFlagged(MessageSequence.fromId(mimeMessage.sequenceId));
```
