### ISSUE TITLE
Parse a MimeMessage from a raw message String

### ISSUE THREAD

**Issue by TheOneWithTheBraid** [Enough-Software/enough_mail#95]
In my use case, I have PGP encrypted messages which I manually decrypt. I would really like to create a new mime message from the decrypted result. Is this somehow possible?

**Comment by TheOneWithTheBraid** [comment]
@robert-virkus Do you have any idea how to manually parse a MIME message from a String?

**Comment by robert-virkus** [comment]
Sorry for late answer. Use `MimeMessage()..bodyRaw = text;` to create a new mesage based on a `String`. If that helps please close this issue.

**Comment by robert-virkus** [comment]
There is now also the `MimeMessage.parseFromText(String text)` method available.

**Comment by jialin97** [comment]
Is there any limitation for the ```MimeMessage.parseFromText(String text)```, because when I try to parse a huge ```Text```, the app will be not responding, but it works well with shorter ```String``` ...
