### ISSUE TITLE
FormatException when decoding subject

### ISSUE THREAD

**Issue by andreademasi** [Enough-Software/enough_mail#96]
I'm trying to decode the subject header from a MimeMessage which is encoded with `iso-8859-15`. When decoding a Format Exception is thrown. In my case a string like `Test=20string=BFchar` will throw: `FormatException: Unexpected extension byte`.
This might have something to do with issue #55 
EDIT: Looks like using the Latin1 codec leads to fewer exceptions

**Comment by robert-virkus** [comment]
Hi Andrea, yes having very little character codes in Dart is currently a major pain. What do you think, should I stick to `latin1` / `iso-8859-1` for all `iso-8859-X` encoded messages for now?

**Comment by robert-virkus** [comment]
enough_mail now supports all ISO-8859 encodings.
