### ISSUE TITLE
Hi sir , pleas How can I use enough_mail to delet maile with imap protocole  ? or exist any methodes to get controle of mails 

### ISSUE THREAD

**Issue by salahdine2020** [Enough-Software/enough_mail#99]

**Comment by robert-virkus** [comment]
You can call `await imapClient.markDeleted(sequence)`, for example. Or move the message to trash, which is more complex. Please close if that has solved your problem.

**Comment by salahdine2020** [comment]
thanx for reply rbert i used this method it helps me to handle the delete processe is the same as u said :

  void deleteMessage({MimeMessage message, email, password}) async {
    // MessageSequence messageSequence = MessageSequence();
    //var inboxResponse = await client.selectInbox();
    //ImapClient client = ImapClient();
    var client = ImapClient(isLogEnabled: true);
    await client.connectToServer(imapServerHost, imapServerPort, isSecure: isImapServerSecure);
    var loginResponse = await client.login(email, password);
    if (loginResponse.isOkStatus) {
      var listResponse = await client.listMailboxes();
      if (listResponse.isOkStatus) {
       // print('mailboxes: ${listResponse.result}');
      }
      var inboxResponse = await client.selectInbox();
      if (inboxResponse.isOkStatus) {
        MessageSequence messageSequence = MessageSequence.fromMessage(message);
        messageSequence.addSequenceId(message);
        //var deleteResponse = await client.expunge();
        var deleteResponse = await client.markDeleted(messageSequence,silent: true);
        deleteResponse.isOkStatus;
        print('Going throught the deleted');
      } else {
        print('what is wrong');
      }
    }
  }

**Comment by robert-virkus** [comment]
Very good, have fun!
